# jitter_shimmer.praat — generate the Praat golden values for sadda's
# B4 (jitter + shimmer) validation suite.
#
# Reads every *.wav in the fixtures directory and writes one TSV row per
# file with Praat's standard jitter/shimmer measures, using the default
# Voice-report parameters (period floor 0.1 ms, ceiling 20 ms, max period
# factor 1.3, max amplitude factor 1.6) and a 75–600 Hz pitch range.
#
# This is the *record of how the target (reference) data was produced*.
# Per the 2026-05-25 clinical-validation-references DEVLOG entry, Praat is
# the primary reference; these values are committed as golden fixtures so
# CI never needs Praat installed. The fixtures are regenerated by running
# this on the WAVs from synth_fixtures.py.
#
# Praat 6.2.09 (February 15 2022).
# Run from the repo root:
#   praat --run crates/engine/tests/clinical/praat/jitter_shimmer.praat \
#         crates/engine/tests/clinical/fixtures

form Measure jitter and shimmer
    sentence fixtures_dir crates/engine/tests/clinical/fixtures
endform

out$ = fixtures_dir$ + "/praat_golden.tsv"
writeFileLine: out$,
    ... "signal", tab$, "jitter_local", tab$, "jitter_rap", tab$, "jitter_ppq5",
    ... tab$, "shimmer_local", tab$, "shimmer_local_db", tab$, "shimmer_apq3",
    ... tab$, "shimmer_apq5", tab$, "hnr_db"

# Voice-report defaults.
shortest = 0.0001
longest = 0.02
max_period_factor = 1.3
max_amp_factor = 1.6
pitch_floor = 75
pitch_ceiling = 600

strings = Create Strings as file list: "list", fixtures_dir$ + "/*.wav"
n = Get number of strings
for i to n
    selectObject: strings
    name$ = Get string: i
    sound = Read from file: fixtures_dir$ + "/" + name$
    stem$ = name$ - ".wav"

    selectObject: sound
    pitch = To Pitch: 0, pitch_floor, pitch_ceiling
    selectObject: sound, pitch
    pp = To PointProcess (cc)

    selectObject: pp
    jit_local = Get jitter (local): 0, 0, shortest, longest, max_period_factor
    jit_rap = Get jitter (rap): 0, 0, shortest, longest, max_period_factor
    jit_ppq5 = Get jitter (ppq5): 0, 0, shortest, longest, max_period_factor

    selectObject: sound, pp
    shim_local = Get shimmer (local): 0, 0, shortest, longest, max_period_factor, max_amp_factor
    shim_db = Get shimmer (local_dB): 0, 0, shortest, longest, max_period_factor, max_amp_factor
    shim_apq3 = Get shimmer (apq3): 0, 0, shortest, longest, max_period_factor, max_amp_factor
    shim_apq5 = Get shimmer (apq5): 0, 0, shortest, longest, max_period_factor, max_amp_factor

    # HNR (B5) — mean of the cross-correlation harmonicity.
    selectObject: sound
    harm = To Harmonicity (cc): 0.01, pitch_floor, 0.1, 1.0
    hnr = Get mean: 0, 0

    appendFileLine: out$, stem$, tab$, jit_local, tab$, jit_rap, tab$, jit_ppq5,
        ... tab$, shim_local, tab$, shim_db, tab$, shim_apq3, tab$, shim_apq5,
        ... tab$, hnr

    removeObject: sound, pitch, pp, harm
endfor
removeObject: strings
writeInfoLine: "Wrote ", n, " rows to ", out$
