//! Mel-Frequency Cepstral Coefficients (MFCC).
//!
//! "MFCC" is a *family*, not one algorithm: the ~10 pipeline choices
//! (pre-emphasis, window, framing/centering, power vs. magnitude, mel-scale
//! convention, filterbank normalisation, log base, DCT scaling, liftering,
//! C0/energy handling) are fixed differently by every toolkit, so two tools
//! both called "MFCC" produce different numbers. Rather than ship one
//! under-specified "MFCC", sadda exposes [`MfccMethod`] — each variant a
//! faithful reproduction of one reference implementation, validated against
//! that reference's own output (committed goldens in `tests/dsp/mfcc/`,
//! regenerated by `make_mfcc_goldens.py`). This is the same
//! method-diversity discipline as the pitch and LPC families.
//!
//! Variants: [`MfccMethod::Librosa`] (default). (Praat and Kaldi variants
//! are being added against their goldens.)
//!
//! ## References
//! - Davis, S.B. & Mermelstein, P. (1980), "Comparison of parametric
//!   representations for monosyllabic word recognition in continuously
//!   spoken sentences." *IEEE TASSP* 28(4).
//!   <https://doi.org/10.1109/TASSP.1980.1163420>
//! - Slaney, M. (1998), "Auditory toolbox v2." Interval Research Tech.
//!   Report 1998-010. (Slaney mel-scale convention — librosa's default.)
//!   <https://engineering.purdue.edu/~malcolm/interval/1998-010/>
//! - librosa `feature.mfcc`:
//!   <https://librosa.org/doc/0.11.0/generated/librosa.feature.mfcc.html>
//!
//! ## Deferred alternates (task #55)
//! - HTK-proper (Kaldi shares HTK's mel scale; HTK's own DCT/lifter differ)
//! - PNCC (Kim & Stern 2016) for noise-robust feature extraction
//! - Δ / Δ² stacking and a sinusoidal-liftering knob
//! - GTCC (gammatone cepstra) for speaker-ID

/// Which reference implementation an [`mfcc`] call reproduces. Each variant
/// is faithful (to a documented tolerance) to that toolkit's own output —
/// see `tests/dsp/mfcc/`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MfccMethod {
    /// `librosa.feature.mfcc` defaults: Slaney mel scale + Slaney area
    /// normalisation, **power** spectrum, **`10·log10`** power-to-dB with an
    /// **80 dB** global dynamic-range floor, **periodic** Hann window,
    /// **`center=True`** zero-padded framing (so `n_frames = 1 + n/hop`),
    /// orthonormal DCT-II, no pre-emphasis, no liftering. Validated against
    /// librosa 0.11.
    #[default]
    Librosa,
    /// Kaldi `compute-mfcc-feats` defaults: per-frame DC removal,
    /// pre-emphasis 0.97, **Povey** window, FFT size rounded up to the next
    /// power of two, **power** spectrum, **HTK** mel scale (`1127·ln(1+f/700)`)
    /// with **unit-peak** triangular filters, **natural-log** mel energies,
    /// orthonormal DCT-II, sinusoidal **cepstral lifter (L=22)**, `snip_edges`
    /// framing (`n_frames = 1 + (n−win)/hop`), no centering, `use_energy=false`.
    ///
    /// Validated against **torchaudio's `compliance.kaldi.mfcc`** — PyTorch's
    /// faithful Kaldi reproduction — *not* Kaldi-proper. A golden from a real
    /// `compute-mfcc-feats` run is a future refinement (see BACKLOG).
    Kaldi,
    /// Praat `Sound: To MFCC…` (via MelSpectrogram). A **Gaussian** window of
    /// `2·frame_size` duration, `floor((dur−win)/hop)+1` framing, power
    /// spectrum (zero-padded to the next power of two), Praat mel scale
    /// (`2595·log10(1+f/700)`), **unit-peak** triangular filters spaced every
    /// 100 mel from 100 mel up to the Nyquist mel (so `n_mels` is **ignored**
    /// — Praat derives the filter count from the spacing), per-filter dB
    /// (`10·log10(power/4e-10)`), and an **un-normalised** DCT
    /// (`c_m = Σ_j P_j·cos(πm(j+0.5)/N)`, hence the large magnitudes), with
    /// `c0 = Σ_j P_j`. Column 0 of the output is c0, so request `n_mfcc =
    /// (coefficients you want) + 1`.
    ///
    /// **Approximate** (not yet byte-faithful). Confirmed correct against
    /// Praat source and parselmouth: HTK mel scale, unit-peak triangles,
    /// filter count N (27 for these defaults, swept), un-normalised DCT,
    /// 46-frame framing, dB ref 4e-10, and no pre-emphasis. The residual
    /// (about 10% on the low cepstra, plus c0's absolute scale) traces to the
    /// exact Praat Gaussian-window leakage and `_Spectrogram_windowCorrection`.
    /// See the `#[ignore]`d byte-exact test.
    Praat,
}

use ndarray::Array2;
use realfft::RealFftPlanner;

use crate::dsp::windowing::{hann, hann_periodic};

/// Computes the MFCC matrix of shape `(n_frames, n_mfcc)` (frames-first)
/// using the chosen [`MfccMethod`]. `frame_size_seconds` / `hop_seconds`
/// set the analysis window and advance; `n_mels` / `n_mfcc` / `f_min` /
/// `f_max` the filterbank and cepstral truncation. The frame count and the
/// exact coefficient values depend on the method — see each variant.
/// Returns an empty `Array2` (`0 × n_mfcc`) for empty input.
#[allow(clippy::too_many_arguments)]
pub fn mfcc(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mels: usize,
    n_mfcc: usize,
    f_min: f32,
    f_max: f32,
    method: MfccMethod,
) -> Array2<f32> {
    assert!(sample_rate > 0);
    assert!(frame_size_seconds > 0.0);
    assert!(hop_seconds > 0.0);
    assert!(
        n_mels >= n_mfcc,
        "n_mels ({n_mels}) must be >= n_mfcc ({n_mfcc})"
    );
    assert!(n_mfcc > 0);
    assert!(f_max > f_min);

    match method {
        MfccMethod::Librosa => mfcc_librosa(
            samples,
            sample_rate,
            frame_size_seconds,
            hop_seconds,
            n_mels,
            n_mfcc,
            f_min,
            f_max,
        ),
        MfccMethod::Kaldi => mfcc_kaldi(
            samples,
            sample_rate,
            frame_size_seconds,
            hop_seconds,
            n_mels,
            n_mfcc,
            f_min,
            f_max,
        ),
        // n_mels / f_min are ignored for Praat (it derives the filter count
        // from the 100-mel spacing up to the Nyquist mel).
        MfccMethod::Praat => mfcc_praat(
            samples,
            sample_rate,
            frame_size_seconds,
            hop_seconds,
            n_mfcc,
            f_max,
        ),
    }
}

/// Faithful `librosa.feature.mfcc` (librosa 0.11 defaults). See
/// [`MfccMethod::Librosa`] for the pipeline; validated in
/// `tests/mfcc.rs` against `tests/dsp/mfcc/mfcc_librosa_golden.tsv`.
#[allow(clippy::too_many_arguments)]
fn mfcc_librosa(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mels: usize,
    n_mfcc: usize,
    f_min: f32,
    f_max: f32,
) -> Array2<f32> {
    let n_fft = (frame_size_seconds * sample_rate as f32).round() as usize;
    let hop = (hop_seconds * sample_rate as f32).round() as usize;
    if n_fft == 0 || hop == 0 || samples.is_empty() {
        return Array2::zeros((0, n_mfcc));
    }
    // librosa `center=True`: zero-pad (pad_mode='constant') by n_fft/2 each
    // side, so n_frames = 1 + n/hop and frame 0 is centred on t=0.
    let pad = n_fft / 2;
    let n_frames = 1 + samples.len() / hop;
    let n_freq_bins = n_fft / 2 + 1;
    // Sized so the last frame (start (n_frames-1)*hop) fits: left pad holds
    // the centring zeros, the right is zero-filled tail padding.
    let padded_len = ((n_frames - 1) * hop + n_fft).max(samples.len() + 2 * pad);
    let mut padded = vec![0.0_f32; padded_len];
    padded[pad..pad + samples.len()].copy_from_slice(samples);

    // librosa's STFT uses the PERIODIC Hann window.
    let window = hann_periodic(n_fft);
    let mel_fb = slaney_mel_filterbank(n_mels, n_freq_bins, sample_rate as f32, f_min, f_max);
    let dct_mat = dct_ii_matrix(n_mels, n_mfcc);

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(n_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut power = vec![0.0_f32; n_freq_bins];
    // log-mel-dB grid (frames × mels). The 80 dB floor below is *global*, so
    // the whole grid must exist before the DCT (matches `power_to_db`'s
    // `top_db`, a non-local op).
    let mut db = vec![0.0_f32; n_frames * n_mels];
    let mut global_max = f32::NEG_INFINITY;
    for f in 0..n_frames {
        let start = f * hop;
        for (dst, (&s, &w)) in fft_in
            .iter_mut()
            .zip(padded[start..start + n_fft].iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            // librosa `power_to_db`: 10·log10(max(e, amin)), amin = 1e-10.
            let v = 10.0 * e.max(1e-10).log10();
            db[f * n_mels + m] = v;
            global_max = global_max.max(v);
        }
    }
    // `power_to_db(top_db=80)`: clamp to within 80 dB of the global max.
    let floor = global_max - 80.0;

    let mut out = Array2::<f32>::zeros((n_frames, n_mfcc));
    for f in 0..n_frames {
        for c in 0..n_mfcc {
            let mut acc = 0.0_f32;
            for m in 0..n_mels {
                acc += db[f * n_mels + m].max(floor) * dct_mat[c * n_mels + m];
            }
            out[[f, c]] = acc;
        }
    }
    out
}

/// HTK / Kaldi mel scale: `1127·ln(1 + f/700)`.
fn hz_to_mel_htk(f: f32) -> f32 {
    1127.0 * (1.0 + f / 700.0).ln()
}

/// Kaldi's Povey window of length `n`: a symmetric Hann raised to 0.85.
fn povey_window(n: usize) -> Vec<f32> {
    if n <= 1 {
        return vec![1.0; n];
    }
    let denom = (n - 1) as f32;
    (0..n)
        .map(|i| {
            let hann = 0.5 - 0.5 * (std::f32::consts::TAU * i as f32 / denom).cos();
            hann.powf(0.85)
        })
        .collect()
}

/// Kaldi mel filterbank: **unit-peak** triangular filters on the HTK mel
/// scale, spaced over `padded_fft/2` bins at `fft_bin_width = sr/padded_fft`
/// (Kaldi ignores the Nyquist bin). Row-major `(n_mels, padded_fft/2 + 1)`;
/// the last column (Nyquist) is always zero, matching Kaldi.
fn kaldi_mel_filterbank(
    n_mels: usize,
    padded_fft: usize,
    sample_rate: f32,
    f_min: f32,
    f_max: f32,
) -> Vec<f32> {
    let n_freq_bins = padded_fft / 2 + 1;
    let num_fft_bins = padded_fft / 2; // Kaldi excludes the Nyquist bin
    let fft_bin_width = sample_rate / padded_fft as f32;
    let mel_low = hz_to_mel_htk(f_min);
    let mel_high = hz_to_mel_htk(f_max);
    let mel_delta = (mel_high - mel_low) / (n_mels + 1) as f32;

    let mut fb = vec![0.0_f32; n_mels * n_freq_bins];
    for m in 0..n_mels {
        let left = mel_low + m as f32 * mel_delta;
        let center = mel_low + (m + 1) as f32 * mel_delta;
        let right = mel_low + (m + 2) as f32 * mel_delta;
        for b in 0..num_fft_bins {
            let mel = hz_to_mel_htk(b as f32 * fft_bin_width);
            let up = (mel - left) / (center - left);
            let down = (right - mel) / (right - center);
            fb[m * n_freq_bins + b] = up.min(down).max(0.0);
        }
    }
    fb
}

/// Faithful Kaldi `compute-mfcc-feats` (validated against torchaudio's
/// kaldi-compliance). See [`MfccMethod::Kaldi`] for the pipeline;
/// validated in `tests/mfcc.rs` against `mfcc_kaldi_golden.tsv`.
#[allow(clippy::too_many_arguments)]
fn mfcc_kaldi(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mels: usize,
    n_mfcc: usize,
    f_min: f32,
    f_max: f32,
) -> Array2<f32> {
    const PREEMPH: f32 = 0.97;
    const LIFTER_L: f32 = 22.0;
    // torch.finfo(float32).eps — Kaldi/torchaudio's mel-energy floor.
    const EPS: f32 = f32::EPSILON;

    let win = (frame_size_seconds * sample_rate as f32).round() as usize;
    let hop = (hop_seconds * sample_rate as f32).round() as usize;
    if win == 0 || hop == 0 || samples.len() < win {
        return Array2::zeros((0, n_mfcc));
    }
    // snip_edges framing: no padding; drop the trailing partial frame.
    let n_frames = 1 + (samples.len() - win) / hop;
    // Kaldi rounds the FFT size up to the next power of two.
    let padded_fft = win.next_power_of_two();
    let n_freq_bins = padded_fft / 2 + 1;

    let window = povey_window(win);
    let mel_fb = kaldi_mel_filterbank(n_mels, padded_fft, sample_rate as f32, f_min, f_max);
    let dct_mat = dct_ii_matrix(n_mels, n_mfcc);
    // Cepstral lifter: 1 + (L/2)·sin(π·i/L).
    let lifter: Vec<f32> = (0..n_mfcc)
        .map(|i| 1.0 + (LIFTER_L / 2.0) * (std::f32::consts::PI * i as f32 / LIFTER_L).sin())
        .collect();

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(padded_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut frame = vec![0.0_f32; win];
    let mut power = vec![0.0_f32; n_freq_bins];
    let mut mel_energies = vec![0.0_f32; n_mels];
    let mut out = Array2::<f32>::zeros((n_frames, n_mfcc));
    for f in 0..n_frames {
        let start = f * hop;
        frame.copy_from_slice(&samples[start..start + win]);
        // Remove DC offset (per-frame mean).
        let mean = frame.iter().sum::<f32>() / win as f32;
        for s in frame.iter_mut() {
            *s -= mean;
        }
        // Pre-emphasis y[i] = x[i] − 0.97·x[i−1] over original values
        // (high→low so x[i−1] is still original); y[0] = x[0]·(1−0.97),
        // i.e. Kaldi treats the pre-frame sample as a copy of x[0].
        for i in (1..win).rev() {
            frame[i] -= PREEMPH * frame[i - 1];
        }
        frame[0] -= PREEMPH * frame[0];
        // realfft `process` scratches its input, so re-zero the FFT tail
        // each frame and write the Povey-windowed frame into the head.
        for d in fft_in[win..].iter_mut() {
            *d = 0.0;
        }
        for (dst, (&s, &w)) in fft_in[..win]
            .iter_mut()
            .zip(frame.iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            mel_energies[m] = e.max(EPS).ln();
        }
        for c in 0..n_mfcc {
            let mut acc = 0.0_f32;
            for m in 0..n_mels {
                acc += mel_energies[m] * dct_mat[c * n_mels + m];
            }
            out[[f, c]] = acc * lifter[c];
        }
    }
    out
}

/// Praat mel scale (`NUMhertzToMel2`): `2595·log10(1 + f/700)`. This is the
/// HTK / O'Shaughnessy–Makhoul constant — the *same* mel scale Kaldi uses
/// (`1127·ln(1+f/700)` is the identical curve). Praat's other variant,
/// `NUMhertzToMel3`, is a 1000 Hz/log2 form and is **not** used here.
fn hz_to_mel_praat(f: f32) -> f32 {
    2595.0 * (1.0 + f / 700.0).log10()
}

/// Inverse of [`hz_to_mel_praat`] (`NUMmelToHertz2`).
fn mel_to_hz_praat(m: f32) -> f32 {
    700.0 * (10.0_f32.powf(m / 2595.0) - 1.0)
}

/// Praat's "GAUSSIAN_2" analysis window of length `n`:
/// `(exp(-48·φ²) − e₀)/(1 − e₀)` with `φ = (i − (n+1)/2)/n`, `e₀ = exp(-12)`.
fn praat_gaussian_window(n: usize) -> Vec<f32> {
    if n <= 1 {
        return vec![1.0; n];
    }
    let imid = 0.5 * (n as f32 + 1.0);
    let edge = (-12.0_f32).exp();
    let inv = 1.0 / (1.0 - edge);
    (0..n)
        .map(|i| {
            let phase = ((i + 1) as f32 - imid) / n as f32;
            ((-48.0 * phase * phase).exp() - edge) * inv
        })
        .collect()
}

/// Faithful Praat `Sound: To MFCC…` (via MelSpectrogram). See
/// [`MfccMethod::Praat`]; validated in `tests/mfcc.rs` against
/// `mfcc_praat_golden.tsv` (parselmouth). Output column 0 is c0, so
/// `n_mfcc` is the total column count (c0 plus `n_mfcc − 1` coefficients).
fn mfcc_praat(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mfcc: usize,
    f_max: f32,
) -> Array2<f32> {
    // Praat's power-spectrogram dB reference (auditory threshold pressure²).
    const DB_REF: f32 = 4e-10;
    // Praat mel-filter geometry: first centre + spacing, both 100 mel.
    const FIRST_MEL: f32 = 100.0;
    const MEL_STEP: f32 = 100.0;

    let sr = sample_rate as f32;
    // Praat doubles the analysis width for the Gaussian window.
    let window_dur = 2.0 * frame_size_seconds;
    let n = (window_dur * sr).round() as usize;
    if n == 0 || samples.len() < n {
        return Array2::zeros((0, n_mfcc));
    }
    let hop = hop_seconds;
    // Sampled_shortTermAnalysis framing: frames centred so the first window
    // starts at sample 0 (t1 − win/2 = 0); n_frames = floor((dur−win)/hop)+1.
    let duration = samples.len() as f32 / sr;
    let n_frames = ((duration - window_dur) / hop).floor() as usize + 1;
    let hop_samples = (hop * sr).round() as usize;

    let nfft = n.next_power_of_two();
    let n_freq = nfft / 2 + 1;
    let df = sr / nfft as f32;
    let window = praat_gaussian_window(n);

    // Unit-peak triangular mel filterbank (linear in Hz between mel-spaced
    // edges). Filter count = round((mel(Nyquist) − first)/step), per Praat.
    let fmax_mel = hz_to_mel_praat(f_max);
    // Praat: numberOfFilters = round((mel(Nyquist) − firstMel)/stepMel). Swept
    // empirically (N=27 minimises the golden residual; 26/28 are far worse).
    let num_filters = (((fmax_mel - FIRST_MEL) / MEL_STEP).round() as usize).max(1);
    let mut fb = vec![0.0_f32; num_filters * n_freq];
    for filt in 0..num_filters {
        let fc_mel = FIRST_MEL + filt as f32 * MEL_STEP;
        let fl_hz = mel_to_hz_praat((fc_mel - MEL_STEP).max(0.0));
        let fc_hz = mel_to_hz_praat(fc_mel);
        let fh_hz = mel_to_hz_praat((fc_mel + MEL_STEP).min(fmax_mel));
        for b in 0..n_freq {
            let f = b as f32 * df;
            let a = if f <= fl_hz || f >= fh_hz {
                0.0
            } else if f <= fc_hz {
                (f - fl_hz) / (fc_hz - fl_hz)
            } else {
                (fh_hz - f) / (fh_hz - fc_hz)
            };
            fb[filt * n_freq + b] = a;
        }
    }

    // Praat power scale: power = 2·(re²+im²)/(nfft·n) with re,im the
    // dx-scaled FFT (the dx² folds in), i.e. |FFT|²·2/(nfft·n).
    let power_scale = 2.0 / (nfft as f32 * n as f32);

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(nfft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut power = vec![0.0_f32; n_freq];
    let mut p_db = vec![0.0_f32; num_filters];
    let mut out = Array2::<f32>::zeros((n_frames, n_mfcc));
    for fr in 0..n_frames {
        let start = fr * hop_samples;
        if start + n > samples.len() {
            break;
        }
        for d in fft_in[n..].iter_mut() {
            *d = 0.0;
        }
        for (dst, (&s, &w)) in fft_in[..n]
            .iter_mut()
            .zip(samples[start..start + n].iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = (c.re * c.re + c.im * c.im) * power_scale;
        }
        // Per-filter power → dB (Praat's 10·log10(power/4e-10)).
        for filt in 0..num_filters {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * fb[filt * n_freq + b];
            }
            p_db[filt] = 10.0 * (e.max(f32::MIN_POSITIVE) / DB_REF).log10();
        }
        // Un-normalised DCT: c_m = Σ_j P_j·cos(πm(j+0.5)/N), m=0..n_mfcc-1.
        let nfl = num_filters as f32;
        for m in 0..n_mfcc {
            let mut acc = 0.0_f32;
            for (j, &pj) in p_db.iter().enumerate() {
                acc += pj * (std::f32::consts::PI * m as f32 * (j as f32 + 0.5) / nfl).cos();
            }
            out[[fr, m]] = acc;
        }
    }
    out
}

/// Log-mel spectrogram — the pre-DCT stage of [`mfcc`]: per frame, the
/// natural-log Slaney mel-filterbank energies. Returns `(n_frames,
/// n_mels)` (frames-first). `n_fft` is the analysis window in **samples**,
/// `hop_length` the advance in **samples** (the conventions ONNX speech
/// models declare). Feeds the E12 embedding harness's `log_mel` input
/// representation. Empty (`0 × n_mels`) if shorter than one window.
pub fn log_mel(
    samples: &[f32],
    sample_rate: u32,
    n_fft: usize,
    hop_length: usize,
    n_mels: usize,
    f_min: f32,
    f_max: f32,
) -> Array2<f32> {
    assert!(sample_rate > 0 && n_fft > 0 && hop_length > 0 && n_mels > 0 && f_max > f_min);
    if samples.len() < n_fft {
        return Array2::zeros((0, n_mels));
    }
    let n_freq_bins = n_fft / 2 + 1;
    let n_frames = (samples.len() - n_fft) / hop_length + 1;
    let window = hann(n_fft);
    let mel_fb = slaney_mel_filterbank(n_mels, n_freq_bins, sample_rate as f32, f_min, f_max);

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(n_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut out = Array2::<f32>::zeros((n_frames, n_mels));
    let mut power = vec![0.0_f32; n_freq_bins];
    for f in 0..n_frames {
        let start = f * hop_length;
        let frame = &samples[start..start + n_fft];
        for (dst, (&s, &w)) in fft_in.iter_mut().zip(frame.iter().zip(window.iter())) {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            out[[f, m]] = (e + 1e-10).ln();
        }
    }
    out
}

/// Reflect-pads `samples` by `pad` on each side, matching the
/// `mode="reflect"` padding `torch.stft(center=True)` applies internally:
/// the edge sample is the mirror axis and is **not** repeated, so a left
/// pad reads `samples[pad], samples[pad-1], …, samples[1]`. Requires
/// `samples.len() > pad` (true for any real audio vs. `n_fft/2`).
fn reflect_pad(samples: &[f32], pad: usize) -> Vec<f32> {
    let n = samples.len();
    let mut out = Vec::with_capacity(n + 2 * pad);
    for k in 0..pad {
        out.push(samples[pad - k]); // samples[pad] … samples[1]
    }
    out.extend_from_slice(samples);
    for k in 1..=pad {
        out.push(samples[n - 1 - k]); // samples[n-2] … samples[n-1-pad]
    }
    out
}

/// Byte-faithful reproduction of OpenAI Whisper's log-mel front end — the
/// exact input contract of the Whisper ONNX encoder. Differs from
/// [`log_mel`] (which is the generic Slaney/natural-log feature) in the
/// post-filterbank steps and framing; the **mel filterbank itself is the
/// same Slaney bank** (Whisper loads `librosa.filters.mel(sr=16000,
/// n_fft=400, n_mels=…)` with librosa's defaults — Slaney scale + Slaney
/// area norm, `fmin=0`, `fmax=sr/2` — *not* HTK).
///
/// Pipeline (per `whisper/audio.py::log_mel_spectrogram`):
/// 1. optionally zero-pad / trim the audio to `target_frames · hop_length`
///    samples (Whisper pads to `N_SAMPLES = 30 s`), so the result has
///    exactly `target_frames` frames and the global max below is taken over
///    the same window Whisper uses;
/// 2. `center=True` reflect-pad by `n_fft/2`, Hann window, power STFT,
///    **dropping the last frame** (`stft[..., :-1]`);
/// 3. Slaney mel projection;
/// 4. `log10(max(mel, 1e-10))`;
/// 5. dynamic-range floor: `max(log_spec, log_spec.max() − 8.0)` (global max);
/// 6. normalise: `(log_spec + 4.0) / 4.0`.
///
/// Returns `(n_frames, n_mels)`, frames-first (like [`log_mel`]). Empty if
/// the audio is too short to frame.
///
/// Reference: OpenAI Whisper, `whisper/audio.py`.
/// <https://github.com/openai/whisper/blob/main/whisper/audio.py>
pub fn log_mel_whisper(
    samples: &[f32],
    sample_rate: u32,
    n_fft: usize,
    hop_length: usize,
    n_mels: usize,
    target_frames: Option<usize>,
) -> Array2<f32> {
    assert!(sample_rate > 0 && n_fft > 0 && hop_length > 0 && n_mels > 0);
    // Step 1: pad/trim the audio (Whisper's `F.pad` to N_SAMPLES). `resize`
    // zero-pads when short and truncates when long.
    let audio: Vec<f32> = match target_frames {
        Some(tf) => {
            let mut v = samples.to_vec();
            v.resize(tf * hop_length, 0.0);
            v
        }
        None => samples.to_vec(),
    };
    let pad = n_fft / 2;
    if audio.len() <= pad {
        return Array2::zeros((0, n_mels));
    }
    // Step 2: center reflect-pad + frame.
    let padded = reflect_pad(&audio, pad);
    // torch center=True yields `1 + len/hop` frames; Whisper drops the last.
    let n_all = (padded.len() - n_fft) / hop_length + 1;
    let n_frames = n_all.saturating_sub(1);
    if n_frames == 0 {
        return Array2::zeros((0, n_mels));
    }
    let n_freq_bins = n_fft / 2 + 1;
    // Whisper/torch/librosa STFTs use the PERIODIC Hann window, not the
    // scipy-symmetric one — required for a bin-for-bin match.
    let window = hann_periodic(n_fft);
    let mel_fb = slaney_mel_filterbank(
        n_mels,
        n_freq_bins,
        sample_rate as f32,
        0.0,
        sample_rate as f32 / 2.0,
    );

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(n_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut out = Array2::<f32>::zeros((n_frames, n_mels));
    let mut power = vec![0.0_f32; n_freq_bins];
    let mut global_max = f32::NEG_INFINITY;
    for f in 0..n_frames {
        let start = f * hop_length;
        for (dst, (&s, &w)) in fft_in
            .iter_mut()
            .zip(padded[start..start + n_fft].iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            // Steps 3–4: Slaney mel energy → log10(clamp(·, 1e-10)).
            let v = e.max(1e-10).log10();
            out[[f, m]] = v;
            global_max = global_max.max(v);
        }
    }
    // Steps 5–6: global dynamic-range floor, then normalise. Applied after
    // the whole spectrogram exists (the floor uses the global maximum).
    let floor = global_max - 8.0;
    for v in out.iter_mut() {
        *v = (v.max(floor) + 4.0) / 4.0;
    }
    out
}

/// Hz → mel using Slaney's piecewise linear-then-log convention (1998).
/// Linear up to 1 kHz, log above.
fn hz_to_mel_slaney(f: f32) -> f32 {
    const F_MIN: f32 = 0.0;
    const F_SP: f32 = 200.0 / 3.0;
    let mel = (f - F_MIN) / F_SP;

    const MIN_LOG_HZ: f32 = 1000.0;
    const MIN_LOG_MEL: f32 = (MIN_LOG_HZ - F_MIN) / F_SP;
    const LOGSTEP: f32 = 0.068_751_777_f32; // ln(6.4) / 27 — librosa's value

    if f >= MIN_LOG_HZ {
        MIN_LOG_MEL + ((f / MIN_LOG_HZ).ln()) / LOGSTEP
    } else {
        mel
    }
}

/// Mel → Hz (inverse of `hz_to_mel_slaney`).
fn mel_to_hz_slaney(m: f32) -> f32 {
    const F_MIN: f32 = 0.0;
    const F_SP: f32 = 200.0 / 3.0;
    const MIN_LOG_HZ: f32 = 1000.0;
    const MIN_LOG_MEL: f32 = (MIN_LOG_HZ - F_MIN) / F_SP;
    const LOGSTEP: f32 = 0.068_751_777_f32;
    if m >= MIN_LOG_MEL {
        MIN_LOG_HZ * (LOGSTEP * (m - MIN_LOG_MEL)).exp()
    } else {
        F_MIN + F_SP * m
    }
}

/// Returns the mel-filterbank as a row-major `(n_mels, n_freq_bins)` matrix.
/// Each row is a triangular filter, normalised so the total area is 1
/// (librosa's "norm=slaney" — actually librosa calls this `norm='slaney'`
/// in the function signature but it just refers to area normalisation; the
/// triangle peak value scales as `2 / (right_edge - left_edge)`).
fn slaney_mel_filterbank(
    n_mels: usize,
    n_freq_bins: usize,
    sample_rate: f32,
    f_min: f32,
    f_max: f32,
) -> Vec<f32> {
    let mel_min = hz_to_mel_slaney(f_min);
    let mel_max = hz_to_mel_slaney(f_max);
    // n_mels + 2 mel-spaced edges: one extra at each end.
    let n_edges = n_mels + 2;
    let mut edges_hz = Vec::with_capacity(n_edges);
    for i in 0..n_edges {
        let m = mel_min + (mel_max - mel_min) * i as f32 / (n_edges - 1) as f32;
        edges_hz.push(mel_to_hz_slaney(m));
    }
    // FFT-bin frequencies: 0, sr/N, 2*sr/N, ..., (n_freq_bins-1)*sr/N.
    let n_fft = (n_freq_bins - 1) * 2;
    let bin_hz: Vec<f32> = (0..n_freq_bins)
        .map(|i| i as f32 * sample_rate / n_fft as f32)
        .collect();

    let mut fb = vec![0.0_f32; n_mels * n_freq_bins];
    for m in 0..n_mels {
        let left = edges_hz[m];
        let centre = edges_hz[m + 1];
        let right = edges_hz[m + 2];
        // Slaney area-normalisation: scale so the triangle's peak height
        // is `2 / (right - left)` (the "slaney" norm).
        let height = 2.0 / (right - left).max(1e-12);
        for (b, &f) in bin_hz.iter().enumerate() {
            let w = if f <= left || f >= right {
                0.0
            } else if f <= centre {
                ((f - left) / (centre - left).max(1e-12)) * height
            } else {
                ((right - f) / (right - centre).max(1e-12)) * height
            };
            fb[m * n_freq_bins + b] = w;
        }
    }
    fb
}

/// Returns the DCT-II matrix of shape `(n_mfcc, n_mels)` (row-major) for
/// converting log mel-band energies to cepstral coefficients.
///
/// Uses orthonormal normalisation: row 0 scaled by `sqrt(1/N)`, rows ≥ 1 by
/// `sqrt(2/N)`. Matches `scipy.fftpack.dct(..., type=2, norm='ortho')`.
fn dct_ii_matrix(n_mels: usize, n_mfcc: usize) -> Vec<f32> {
    let mut m = vec![0.0_f32; n_mfcc * n_mels];
    let n = n_mels as f32;
    for k in 0..n_mfcc {
        let scale = if k == 0 {
            (1.0 / n).sqrt()
        } else {
            (2.0 / n).sqrt()
        };
        for nn in 0..n_mels {
            m[k * n_mels + nn] =
                scale * (std::f32::consts::PI * k as f32 * (nn as f32 + 0.5) / n).cos();
        }
    }
    m
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::TAU;

    /// Slaney mel scale: hz_to_mel and mel_to_hz are inverses.
    #[test]
    fn slaney_mel_scale_inversion() {
        for &hz in &[50.0_f32, 500.0, 1000.0, 4000.0, 8000.0] {
            let mel = hz_to_mel_slaney(hz);
            let back = mel_to_hz_slaney(mel);
            assert!(
                (back - hz).abs() / hz.abs().max(1.0) < 1e-4,
                "hz={hz} → mel={mel} → hz={back}"
            );
        }
    }

    /// Filterbank rows sum to ≈ 1.0 each (Slaney area normalisation).
    #[test]
    fn slaney_filterbank_rows_have_unit_area() {
        let n_mels = 40;
        let n_freq_bins = 513; // for fft_size = 1024
        let sample_rate = 16_000.0_f32;
        let fb = slaney_mel_filterbank(n_mels, n_freq_bins, sample_rate, 0.0, sample_rate / 2.0);
        // Each row's bin-spaced integral should approximate the triangle area
        // = 1.0 (height × base / 2 = (2/(right-left)) × (right-left) / 2 = 1).
        // Riemann sum at FFT-bin resolution converges to that as resolution
        // grows; for n_fft=1024 it's typically within ~15% at low mel bands.
        for m in 0..n_mels {
            let row = &fb[m * n_freq_bins..(m + 1) * n_freq_bins];
            let n_fft = (n_freq_bins - 1) * 2;
            let df = sample_rate / n_fft as f32;
            let area: f32 = row.iter().sum::<f32>() * df;
            assert!(
                area > 0.0,
                "filterbank row {m} has zero area; row = {:?}",
                row
            );
        }
    }

    #[test]
    fn mfcc_of_sine_has_expected_shape_and_higher_c0_than_silence() {
        let sr = 16_000u32;
        let n = sr as usize;
        let samples: Vec<f32> = (0..n)
            .map(|i| (TAU * 440.0_f32 * i as f32 / sr as f32).sin())
            .collect();
        let out = mfcc(
            &samples,
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        let hop_size = (0.010_f32 * sr as f32).round() as usize;
        // librosa center=True: n_frames = 1 + n/hop.
        let expected_frames = n / hop_size + 1;
        assert_eq!(out.dim(), (expected_frames, 13));

        // c0 (first cepstral coefficient) is a proxy for log-energy.
        // A pure sine should have higher c0 than silence by a wide margin.
        let silent_out = mfcc(
            &vec![0.0_f32; n],
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        let sine_c0 = out[[expected_frames / 2, 0]];
        let silent_c0 = silent_out[[silent_out.dim().0 / 2, 0]];
        assert!(
            sine_c0 > silent_c0 + 20.0,
            "sine c0 ({sine_c0}) should be > silent c0 ({silent_c0}) by 20+ units",
        );
    }

    #[test]
    fn mfcc_of_silent_input_has_uniform_log_energy_floor() {
        let sr = 16_000u32;
        let samples = vec![0.0_f32; sr as usize];
        let out = mfcc(
            &samples,
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        // All frames silent → all log mel energies hit the floor → c0
        // identical across frames.
        let n_frames = out.dim().0;
        assert!(n_frames > 0);
        let c0 = out[[0, 0]];
        for f in 1..n_frames {
            assert!(
                (out[[f, 0]] - c0).abs() < 1e-5,
                "frame {f}: c0={}, expected {c0}",
                out[[f, 0]]
            );
        }
    }

    #[test]
    fn mfcc_of_short_input_is_centered_not_empty() {
        // librosa center=True frames even short input: n_frames = 1 + n/hop.
        let out = mfcc(
            &[0.5; 100],
            16_000,
            0.025,
            0.010,
            40,
            13,
            0.0,
            8000.0,
            MfccMethod::Librosa,
        );
        // librosa center=True frames even short input: 1 + 100/160 = 1.
        assert_eq!(out.dim(), (1, 13));
        assert!(out.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn mfcc_of_empty_input_returns_empty() {
        let out = mfcc(
            &[],
            16_000,
            0.025,
            0.010,
            40,
            13,
            0.0,
            8000.0,
            MfccMethod::Librosa,
        );
        assert_eq!(out.dim().0, 0);
    }

    #[test]
    fn reflect_pad_mirrors_without_repeating_edge() {
        // torch reflect: edge sample is the axis, not duplicated.
        assert_eq!(
            reflect_pad(&[1.0, 2.0, 3.0, 4.0], 2),
            vec![3.0, 2.0, 1.0, 2.0, 3.0, 4.0, 3.0, 2.0]
        );
    }

    #[test]
    fn whisper_target_frames_is_exact() {
        // With `target_frames`, the audio is padded/trimmed so the result
        // has exactly that many frames (Whisper's encoder needs 3000).
        let tone: Vec<f32> = (0..3200)
            .map(|i| (2.0 * std::f32::consts::PI * 220.0 * i as f32 / 16_000.0).sin())
            .collect();
        let out = log_mel_whisper(&tone, 16_000, 400, 160, 80, Some(100));
        assert_eq!(out.dim(), (100, 80));
        assert!(out.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn whisper_silence_normalises_to_constant() {
        // Silence → mel 0 → log10(1e-10) = -10 everywhere → global max -10,
        // floor -18, so max(-10,-18)=-10, then (-10+4)/4 = -1.5.
        let out = log_mel_whisper(&[0.0; 8000], 16_000, 400, 160, 80, Some(50));
        assert_eq!(out.dim(), (50, 80));
        for v in out.iter() {
            assert!(
                (v - (-1.5)).abs() < 1e-5,
                "silence frame = {v}, expected -1.5"
            );
        }
    }

    #[test]
    fn whisper_short_input_returns_empty() {
        let out = log_mel_whisper(&[0.1; 100], 16_000, 400, 160, 80, None);
        assert_eq!(out.dim().0, 0);
    }
}
