//! Mel-Frequency Cepstral Coefficients (MFCC).
//!
//! "MFCC" is a *family*, not one algorithm: the ~10 pipeline choices
//! (pre-emphasis, window, framing/centering, power vs. magnitude, mel-scale
//! convention, filterbank normalisation, log base, DCT scaling, liftering,
//! C0/energy handling) are fixed differently by every toolkit, so two tools
//! both called "MFCC" produce different numbers. Rather than ship one
//! under-specified "MFCC", sadda exposes [`MfccMethod`] — each variant a
//! faithful reproduction of one reference implementation, validated against
//! that reference's own output (committed goldens in `tests/dsp/mfcc/`,
//! regenerated by `make_mfcc_goldens.py`). This is the same
//! method-diversity discipline as the pitch and LPC families.
//!
//! Named methods: [`MfccMethod::Librosa`] (default), [`MfccMethod::Kaldi`],
//! [`MfccMethod::Praat`]. For full control — pick a reference preset, then
//! override individual knobs — use [`MfccParams`] + [`mfcc_with_params`]
//! ([`MfccParams::librosa`] / [`kaldi`](MfccParams::kaldi) /
//! [`praat`](MfccParams::praat)). `mfcc(…, Librosa|Kaldi)` dispatches through
//! that unified pipeline; `Praat` keeps a dedicated f64 path (see its docs).
//!
//! ## References
//! - Davis, S.B. & Mermelstein, P. (1980), "Comparison of parametric
//!   representations for monosyllabic word recognition in continuously
//!   spoken sentences." *IEEE TASSP* 28(4).
//!   <https://doi.org/10.1109/TASSP.1980.1163420>
//! - Slaney, M. (1998), "Auditory toolbox v2." Interval Research Tech.
//!   Report 1998-010. (Slaney mel-scale convention — librosa's default.)
//!   <https://engineering.purdue.edu/~malcolm/interval/1998-010/>
//! - librosa `feature.mfcc`:
//!   <https://librosa.org/doc/0.11.0/generated/librosa.feature.mfcc.html>
//!
//! ## Deferred alternates (task #55)
//! - HTK-proper (Kaldi shares HTK's mel scale; HTK's own DCT/lifter differ)
//! - PNCC (Kim & Stern 2016) for noise-robust feature extraction
//! - Δ / Δ² stacking and a sinusoidal-liftering knob
//! - GTCC (gammatone cepstra) for speaker-ID

/// Which reference implementation an [`mfcc`] call reproduces. Each variant
/// is faithful (to a documented tolerance) to that toolkit's own output —
/// see `tests/dsp/mfcc/`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MfccMethod {
    /// `librosa.feature.mfcc` defaults: Slaney mel scale + Slaney area
    /// normalisation, **power** spectrum, **`10·log10`** power-to-dB with an
    /// **80 dB** global dynamic-range floor, **periodic** Hann window,
    /// **`center=True`** zero-padded framing (so `n_frames = 1 + n/hop`),
    /// orthonormal DCT-II, no pre-emphasis, no liftering. Validated against
    /// librosa 0.11.
    #[default]
    Librosa,
    /// Kaldi `compute-mfcc-feats` defaults: per-frame DC removal,
    /// pre-emphasis 0.97, **Povey** window, FFT size rounded up to the next
    /// power of two, **power** spectrum, **HTK** mel scale (`1127·ln(1+f/700)`)
    /// with **unit-peak** triangular filters, **natural-log** mel energies,
    /// orthonormal DCT-II, sinusoidal **cepstral lifter (L=22)**, `snip_edges`
    /// framing (`n_frames = 1 + (n−win)/hop`), no centering, `use_energy=false`.
    ///
    /// Validated against **torchaudio's `compliance.kaldi.mfcc`** — PyTorch's
    /// faithful Kaldi reproduction — *not* Kaldi-proper. A golden from a real
    /// `compute-mfcc-feats` run is a future refinement (see BACKLOG).
    Kaldi,
    /// Praat `Sound: To MFCC…` (via MelSpectrogram). A **Gaussian** window of
    /// `2·frame_size` duration, `floor((dur−win)/hop)+1` framing, power
    /// spectrum (zero-padded to the next power of two), Praat mel scale
    /// (`2595·log10(1+f/700)`), **unit-peak** triangular filters spaced every
    /// 100 mel from 100 mel up to the Nyquist mel (so `n_mels` is **ignored**
    /// — Praat derives the filter count from the spacing), per-filter dB
    /// (`10·log10(power/4e-10)`), and an **un-normalised** DCT
    /// (`c_m = Σ_j P_j·cos(πm(j+0.5)/N)`, hence the large magnitudes), with
    /// `c0 = Σ_j P_j`. Column 0 of the output is c0, so request `n_mfcc =
    /// (coefficients you want) + 1`.
    ///
    /// **Faithful to tolerance, not byte-exact.** Computed in f64 (including
    /// the FFT) with Praat's `_Spectrogram_windowCorrection`. Validated against
    /// parselmouth: typical-frame agreement ≈0.3%, worst-case ≈10 on c1+
    /// (shape) and ≈20 on c0 (energy). Confirmed-exact structure: HTK mel,
    /// unit-peak triangles, N=27 (swept), Gaussian-2 window, framing, dB ref
    /// 4e-10, windowCorrection, no pre-emphasis. The residual is irreducible
    /// FFT-library noise: Praat's un-normalised dB DCT sums `10·log10` of every
    /// filter, so near-empty high filters (≈1e-30) are ill-conditioned and
    /// sub-1e-15 FFT differences (realfft vs Praat's NUMrealft) surface there.
    /// A bit-exact match would require Praat's exact FFT.
    Praat,
}

use ndarray::Array2;
use realfft::RealFftPlanner;

use crate::dsp::windowing::{hann, hann_periodic};

/// Computes the MFCC matrix of shape `(n_frames, n_mfcc)` (frames-first)
/// using the chosen [`MfccMethod`]. `frame_size_seconds` / `hop_seconds`
/// set the analysis window and advance; `n_mels` / `n_mfcc` / `f_min` /
/// `f_max` the filterbank and cepstral truncation. The frame count and the
/// exact coefficient values depend on the method — see each variant.
/// Returns an empty `Array2` (`0 × n_mfcc`) for empty input.
#[allow(clippy::too_many_arguments)]
pub fn mfcc(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mels: usize,
    n_mfcc: usize,
    f_min: f32,
    f_max: f32,
    method: MfccMethod,
) -> Array2<f32> {
    assert!(sample_rate > 0);
    assert!(frame_size_seconds > 0.0);
    assert!(hop_seconds > 0.0);
    assert!(
        n_mels >= n_mfcc,
        "n_mels ({n_mels}) must be >= n_mfcc ({n_mfcc})"
    );
    assert!(n_mfcc > 0);
    assert!(f_max > f_min);

    // Librosa and Kaldi dispatch through the unified MfccParams pipeline
    // (proven equivalent by the `unified_pipeline_*` tests). Praat keeps its
    // dedicated f64 path: its un-normalised dB DCT is precision-sensitive on
    // near-empty filters, needing f64 + windowCorrection the (f32) unified
    // pipeline doesn't carry yet — migrating it awaits the "pipeline → f64"
    // decision. n_mels / f_min are ignored for Praat.
    match method {
        MfccMethod::Librosa => mfcc_with_params(
            samples,
            sample_rate,
            &MfccParams::librosa(
                frame_size_seconds,
                hop_seconds,
                n_mels,
                n_mfcc,
                f_min,
                f_max,
            ),
        ),
        MfccMethod::Kaldi => mfcc_with_params(
            samples,
            sample_rate,
            &MfccParams::kaldi(
                frame_size_seconds,
                hop_seconds,
                n_mels,
                n_mfcc,
                f_min,
                f_max,
            ),
        ),
        MfccMethod::Praat => mfcc_praat(
            samples,
            sample_rate,
            frame_size_seconds,
            hop_seconds,
            n_mfcc,
            f_max,
        ),
    }
}

/// Kaldi's Povey window of length `n`: a symmetric Hann raised to 0.85.
fn povey_window(n: usize) -> Vec<f32> {
    if n <= 1 {
        return vec![1.0; n];
    }
    let denom = (n - 1) as f32;
    (0..n)
        .map(|i| {
            let hann = 0.5 - 0.5 * (std::f32::consts::TAU * i as f32 / denom).cos();
            hann.powf(0.85)
        })
        .collect()
}

/// Praat mel scale (`NUMhertzToMel2`): `2595·log10(1 + f/700)`. This is the
/// HTK / O'Shaughnessy–Makhoul constant — the *same* mel scale Kaldi uses
/// (`1127·ln(1+f/700)` is the identical curve). Praat's other variant,
/// `NUMhertzToMel3`, is a 1000 Hz/log2 form and is **not** used here.
fn hz_to_mel_praat(f: f32) -> f32 {
    2595.0 * (1.0 + f / 700.0).log10()
}

/// Inverse of [`hz_to_mel_praat`] (`NUMmelToHertz2`).
fn mel_to_hz_praat(m: f32) -> f32 {
    700.0 * (10.0_f32.powf(m / 2595.0) - 1.0)
}

/// Praat's "GAUSSIAN_2" analysis window of length `n`:
/// `(exp(-48·φ²) − e₀)/(1 − e₀)` with `φ = (i − (n+1)/2)/n`, `e₀ = exp(-12)`.
fn praat_gaussian_window(n: usize) -> Vec<f32> {
    if n <= 1 {
        return vec![1.0; n];
    }
    let imid = 0.5 * (n as f32 + 1.0);
    let edge = (-12.0_f32).exp();
    let inv = 1.0 / (1.0 - edge);
    (0..n)
        .map(|i| {
            let phase = ((i + 1) as f32 - imid) / n as f32;
            ((-48.0 * phase * phase).exp() - edge) * inv
        })
        .collect()
}

/// Praat `Sound: To MFCC…` (via MelSpectrogram). See [`MfccMethod::Praat`];
/// validated in `tests/mfcc.rs` against `mfcc_praat_golden.tsv` (parselmouth).
/// Output column 0 is c0, so `n_mfcc` is the total column count.
///
/// Computed in **f64** (FFT included): Praat's un-normalised dB DCT sums
/// `10·log10` of *every* filter, so the near-empty high filters' tiny powers
/// dominate the conditioning — f32 underflow there blew the residual up ~5×.
/// The remaining gap to Praat (~few % worst-case) is irreducible FFT-library
/// noise on those tiny values; the typical-frame agreement is ~0.3%.
fn mfcc_praat(
    samples: &[f32],
    sample_rate: u32,
    frame_size_seconds: f32,
    hop_seconds: f32,
    n_mfcc: usize,
    f_max: f32,
) -> Array2<f32> {
    // Praat's power-spectrogram dB reference (auditory threshold pressure²).
    const DB_REF: f64 = 4e-10;
    // Praat mel-filter geometry: first centre + spacing, both 100 mel.
    const FIRST_MEL: f64 = 100.0;
    const MEL_STEP: f64 = 100.0;
    // Praat NUMhertzToMel2 / its inverse, in f64.
    fn hz2mel(f: f64) -> f64 {
        2595.0 * (1.0 + f / 700.0).log10()
    }
    fn mel2hz(m: f64) -> f64 {
        700.0 * (10.0_f64.powf(m / 2595.0) - 1.0)
    }

    let sr = sample_rate as f64;
    // Praat doubles the analysis width for the Gaussian window.
    let window_dur = 2.0 * frame_size_seconds as f64;
    let n = (window_dur * sr).round() as usize;
    if n == 0 || samples.len() < n {
        return Array2::zeros((0, n_mfcc));
    }
    // Sampled_shortTermAnalysis framing: frames centred so the first window
    // starts at sample 0 (t1 − win/2 = 0); n_frames = floor((dur−win)/hop)+1.
    let duration = samples.len() as f64 / sr;
    let n_frames = ((duration - window_dur) / hop_seconds as f64).floor() as usize + 1;
    let hop_samples = (hop_seconds as f64 * sr).round() as usize;

    let nfft = n.next_power_of_two();
    let n_freq = nfft / 2 + 1;
    let df = sr / nfft as f64;

    // Praat GAUSSIAN_2 window (f64) and its mean-square, used for Praat's
    // `_Spectrogram_windowCorrection` (divide power by the window energy).
    let imid = 0.5 * (n as f64 + 1.0);
    let edge = (-12.0_f64).exp();
    let inv = 1.0 / (1.0 - edge);
    let window: Vec<f64> = (0..n)
        .map(|i| {
            let phase = ((i + 1) as f64 - imid) / n as f64;
            ((-48.0 * phase * phase).exp() - edge) * inv
        })
        .collect();
    let window_mean_square = window.iter().map(|w| w * w).sum::<f64>() / n as f64;

    // Unit-peak triangular mel filterbank (linear in Hz between mel-spaced
    // edges). Filter count = round((mel(Nyquist) − first)/step), per Praat
    // (swept: N=27 minimises the residual; 26/28 are far worse).
    let fmax_mel = hz2mel(f_max as f64);
    let num_filters = (((fmax_mel - FIRST_MEL) / MEL_STEP).round() as usize).max(1);
    let mut fb = vec![0.0_f64; num_filters * n_freq];
    for filt in 0..num_filters {
        let fc_mel = FIRST_MEL + filt as f64 * MEL_STEP;
        let fl = mel2hz((fc_mel - MEL_STEP).max(0.0));
        let fc = mel2hz(fc_mel);
        let fh = mel2hz((fc_mel + MEL_STEP).min(fmax_mel));
        for b in 0..n_freq {
            let f = b as f64 * df;
            let a = if f <= fl || f >= fh {
                0.0
            } else if f <= fc {
                (f - fl) / (fc - fl)
            } else {
                (fh - f) / (fh - fc)
            };
            fb[filt * n_freq + b] = a;
        }
    }

    // Praat power scale `2·dx_spec/(xmax−xmin)` folds to |FFT|²·2/(nfft·n);
    // then windowCorrection divides by the window's mean-square.
    let power_scale = 2.0 / (nfft as f64 * n as f64) / window_mean_square;

    let mut planner = RealFftPlanner::<f64>::new();
    let plan = planner.plan_fft_forward(nfft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut power = vec![0.0_f64; n_freq];
    let mut p_db = vec![0.0_f64; num_filters];
    let mut out = Array2::<f32>::zeros((n_frames, n_mfcc));
    for fr in 0..n_frames {
        let start = fr * hop_samples;
        if start + n > samples.len() {
            break;
        }
        for d in fft_in[n..].iter_mut() {
            *d = 0.0;
        }
        for (dst, (&s, &w)) in fft_in[..n]
            .iter_mut()
            .zip(samples[start..start + n].iter().zip(window.iter()))
        {
            *dst = s as f64 * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = (c.re * c.re + c.im * c.im) * power_scale;
        }
        // Per-filter power → dB (Praat's 10·log10(power/4e-10)).
        for filt in 0..num_filters {
            let mut e = 0.0_f64;
            for (b, &p) in power.iter().enumerate() {
                e += p * fb[filt * n_freq + b];
            }
            p_db[filt] = 10.0 * (e.max(f64::MIN_POSITIVE) / DB_REF).log10();
        }
        // Un-normalised DCT: c_m = Σ_j P_j·cos(πm(j+0.5)/N), m=0..n_mfcc-1.
        let nfl = num_filters as f64;
        for m in 0..n_mfcc {
            let mut acc = 0.0_f64;
            for (j, &pj) in p_db.iter().enumerate() {
                acc += pj * (std::f64::consts::PI * m as f64 * (j as f64 + 0.5) / nfl).cos();
            }
            out[[fr, m]] = acc as f32;
        }
    }
    out
}

/// Log-mel spectrogram — the pre-DCT stage of [`mfcc`]: per frame, the
/// natural-log Slaney mel-filterbank energies. Returns `(n_frames,
/// n_mels)` (frames-first). `n_fft` is the analysis window in **samples**,
/// `hop_length` the advance in **samples** (the conventions ONNX speech
/// models declare). Feeds the E12 embedding harness's `log_mel` input
/// representation. Empty (`0 × n_mels`) if shorter than one window.
pub fn log_mel(
    samples: &[f32],
    sample_rate: u32,
    n_fft: usize,
    hop_length: usize,
    n_mels: usize,
    f_min: f32,
    f_max: f32,
) -> Array2<f32> {
    assert!(sample_rate > 0 && n_fft > 0 && hop_length > 0 && n_mels > 0 && f_max > f_min);
    if samples.len() < n_fft {
        return Array2::zeros((0, n_mels));
    }
    let n_freq_bins = n_fft / 2 + 1;
    let n_frames = (samples.len() - n_fft) / hop_length + 1;
    let window = hann(n_fft);
    let mel_fb = slaney_mel_filterbank(n_mels, n_freq_bins, sample_rate as f32, f_min, f_max);

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(n_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut out = Array2::<f32>::zeros((n_frames, n_mels));
    let mut power = vec![0.0_f32; n_freq_bins];
    for f in 0..n_frames {
        let start = f * hop_length;
        let frame = &samples[start..start + n_fft];
        for (dst, (&s, &w)) in fft_in.iter_mut().zip(frame.iter().zip(window.iter())) {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            out[[f, m]] = (e + 1e-10).ln();
        }
    }
    out
}

/// Reflect-pads `samples` by `pad` on each side, matching the
/// `mode="reflect"` padding `torch.stft(center=True)` applies internally:
/// the edge sample is the mirror axis and is **not** repeated, so a left
/// pad reads `samples[pad], samples[pad-1], …, samples[1]`. Requires
/// `samples.len() > pad` (true for any real audio vs. `n_fft/2`).
fn reflect_pad(samples: &[f32], pad: usize) -> Vec<f32> {
    let n = samples.len();
    let mut out = Vec::with_capacity(n + 2 * pad);
    for k in 0..pad {
        out.push(samples[pad - k]); // samples[pad] … samples[1]
    }
    out.extend_from_slice(samples);
    for k in 1..=pad {
        out.push(samples[n - 1 - k]); // samples[n-2] … samples[n-1-pad]
    }
    out
}

/// Byte-faithful reproduction of OpenAI Whisper's log-mel front end — the
/// exact input contract of the Whisper ONNX encoder. Differs from
/// [`log_mel`] (which is the generic Slaney/natural-log feature) in the
/// post-filterbank steps and framing; the **mel filterbank itself is the
/// same Slaney bank** (Whisper loads `librosa.filters.mel(sr=16000,
/// n_fft=400, n_mels=…)` with librosa's defaults — Slaney scale + Slaney
/// area norm, `fmin=0`, `fmax=sr/2` — *not* HTK).
///
/// Pipeline (per `whisper/audio.py::log_mel_spectrogram`):
/// 1. optionally zero-pad / trim the audio to `target_frames · hop_length`
///    samples (Whisper pads to `N_SAMPLES = 30 s`), so the result has
///    exactly `target_frames` frames and the global max below is taken over
///    the same window Whisper uses;
/// 2. `center=True` reflect-pad by `n_fft/2`, Hann window, power STFT,
///    **dropping the last frame** (`stft[..., :-1]`);
/// 3. Slaney mel projection;
/// 4. `log10(max(mel, 1e-10))`;
/// 5. dynamic-range floor: `max(log_spec, log_spec.max() − 8.0)` (global max);
/// 6. normalise: `(log_spec + 4.0) / 4.0`.
///
/// Returns `(n_frames, n_mels)`, frames-first (like [`log_mel`]). Empty if
/// the audio is too short to frame.
///
/// Reference: OpenAI Whisper, `whisper/audio.py`.
/// <https://github.com/openai/whisper/blob/main/whisper/audio.py>
pub fn log_mel_whisper(
    samples: &[f32],
    sample_rate: u32,
    n_fft: usize,
    hop_length: usize,
    n_mels: usize,
    target_frames: Option<usize>,
) -> Array2<f32> {
    assert!(sample_rate > 0 && n_fft > 0 && hop_length > 0 && n_mels > 0);
    // Step 1: pad/trim the audio (Whisper's `F.pad` to N_SAMPLES). `resize`
    // zero-pads when short and truncates when long.
    let audio: Vec<f32> = match target_frames {
        Some(tf) => {
            let mut v = samples.to_vec();
            v.resize(tf * hop_length, 0.0);
            v
        }
        None => samples.to_vec(),
    };
    let pad = n_fft / 2;
    if audio.len() <= pad {
        return Array2::zeros((0, n_mels));
    }
    // Step 2: center reflect-pad + frame.
    let padded = reflect_pad(&audio, pad);
    // torch center=True yields `1 + len/hop` frames; Whisper drops the last.
    let n_all = (padded.len() - n_fft) / hop_length + 1;
    let n_frames = n_all.saturating_sub(1);
    if n_frames == 0 {
        return Array2::zeros((0, n_mels));
    }
    let n_freq_bins = n_fft / 2 + 1;
    // Whisper/torch/librosa STFTs use the PERIODIC Hann window, not the
    // scipy-symmetric one — required for a bin-for-bin match.
    let window = hann_periodic(n_fft);
    let mel_fb = slaney_mel_filterbank(
        n_mels,
        n_freq_bins,
        sample_rate as f32,
        0.0,
        sample_rate as f32 / 2.0,
    );

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(n_fft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();

    let mut out = Array2::<f32>::zeros((n_frames, n_mels));
    let mut power = vec![0.0_f32; n_freq_bins];
    let mut global_max = f32::NEG_INFINITY;
    for f in 0..n_frames {
        let start = f * hop_length;
        for (dst, (&s, &w)) in fft_in
            .iter_mut()
            .zip(padded[start..start + n_fft].iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = c.re * c.re + c.im * c.im;
        }
        for m in 0..n_mels {
            let mut e = 0.0_f32;
            for (b, &p) in power.iter().enumerate() {
                e += p * mel_fb[m * n_freq_bins + b];
            }
            // Steps 3–4: Slaney mel energy → log10(clamp(·, 1e-10)).
            let v = e.max(1e-10).log10();
            out[[f, m]] = v;
            global_max = global_max.max(v);
        }
    }
    // Steps 5–6: global dynamic-range floor, then normalise. Applied after
    // the whole spectrogram exists (the floor uses the global maximum).
    let floor = global_max - 8.0;
    for v in out.iter_mut() {
        *v = (v.max(floor) + 4.0) / 4.0;
    }
    out
}

/// Hz → mel using Slaney's piecewise linear-then-log convention (1998).
/// Linear up to 1 kHz, log above.
fn hz_to_mel_slaney(f: f32) -> f32 {
    const F_MIN: f32 = 0.0;
    const F_SP: f32 = 200.0 / 3.0;
    let mel = (f - F_MIN) / F_SP;

    const MIN_LOG_HZ: f32 = 1000.0;
    const MIN_LOG_MEL: f32 = (MIN_LOG_HZ - F_MIN) / F_SP;
    const LOGSTEP: f32 = 0.068_751_777_f32; // ln(6.4) / 27 — librosa's value

    if f >= MIN_LOG_HZ {
        MIN_LOG_MEL + ((f / MIN_LOG_HZ).ln()) / LOGSTEP
    } else {
        mel
    }
}

/// Mel → Hz (inverse of `hz_to_mel_slaney`).
fn mel_to_hz_slaney(m: f32) -> f32 {
    const F_MIN: f32 = 0.0;
    const F_SP: f32 = 200.0 / 3.0;
    const MIN_LOG_HZ: f32 = 1000.0;
    const MIN_LOG_MEL: f32 = (MIN_LOG_HZ - F_MIN) / F_SP;
    const LOGSTEP: f32 = 0.068_751_777_f32;
    if m >= MIN_LOG_MEL {
        MIN_LOG_HZ * (LOGSTEP * (m - MIN_LOG_MEL)).exp()
    } else {
        F_MIN + F_SP * m
    }
}

/// Returns the mel-filterbank as a row-major `(n_mels, n_freq_bins)` matrix.
/// Each row is a triangular filter, normalised so the total area is 1
/// (librosa's "norm=slaney" — actually librosa calls this `norm='slaney'`
/// in the function signature but it just refers to area normalisation; the
/// triangle peak value scales as `2 / (right_edge - left_edge)`).
fn slaney_mel_filterbank(
    n_mels: usize,
    n_freq_bins: usize,
    sample_rate: f32,
    f_min: f32,
    f_max: f32,
) -> Vec<f32> {
    let mel_min = hz_to_mel_slaney(f_min);
    let mel_max = hz_to_mel_slaney(f_max);
    // n_mels + 2 mel-spaced edges: one extra at each end.
    let n_edges = n_mels + 2;
    let mut edges_hz = Vec::with_capacity(n_edges);
    for i in 0..n_edges {
        let m = mel_min + (mel_max - mel_min) * i as f32 / (n_edges - 1) as f32;
        edges_hz.push(mel_to_hz_slaney(m));
    }
    // FFT-bin frequencies: 0, sr/N, 2*sr/N, ..., (n_freq_bins-1)*sr/N.
    let n_fft = (n_freq_bins - 1) * 2;
    let bin_hz: Vec<f32> = (0..n_freq_bins)
        .map(|i| i as f32 * sample_rate / n_fft as f32)
        .collect();

    let mut fb = vec![0.0_f32; n_mels * n_freq_bins];
    for m in 0..n_mels {
        let left = edges_hz[m];
        let centre = edges_hz[m + 1];
        let right = edges_hz[m + 2];
        // Slaney area-normalisation: scale so the triangle's peak height
        // is `2 / (right - left)` (the "slaney" norm).
        let height = 2.0 / (right - left).max(1e-12);
        for (b, &f) in bin_hz.iter().enumerate() {
            let w = if f <= left || f >= right {
                0.0
            } else if f <= centre {
                ((f - left) / (centre - left).max(1e-12)) * height
            } else {
                ((right - f) / (right - centre).max(1e-12)) * height
            };
            fb[m * n_freq_bins + b] = w;
        }
    }
    fb
}

/// Returns the DCT-II matrix of shape `(n_mfcc, n_mels)` (row-major) for
/// converting log mel-band energies to cepstral coefficients.
///
/// Uses orthonormal normalisation: row 0 scaled by `sqrt(1/N)`, rows ≥ 1 by
/// `sqrt(2/N)`. Matches `scipy.fftpack.dct(..., type=2, norm='ortho')`.
fn dct_ii_matrix(n_mels: usize, n_mfcc: usize) -> Vec<f32> {
    let mut m = vec![0.0_f32; n_mfcc * n_mels];
    let n = n_mels as f32;
    for k in 0..n_mfcc {
        let scale = if k == 0 {
            (1.0 / n).sqrt()
        } else {
            (2.0 / n).sqrt()
        };
        for nn in 0..n_mels {
            m[k * n_mels + nn] =
                scale * (std::f32::consts::PI * k as f32 * (nn as f32 + 0.5) / n).cos();
        }
    }
    m
}

// ============================================================================
// Parameterized MFCC: one pipeline, every knob — "pick a preset, then tweak".
//
// The named `MfccMethod` variants above are opaque faithful reproductions. The
// types below expose the *parameter space* they live in (the 2026-06-29 design):
// every reference difference is a per-stage scalar or enum, so one pipeline
// (`mfcc_with_params`) covers all of them, and the presets (`MfccParams::librosa`
// /`kaldi`/`praat`) are named points validated by the same goldens. This is what
// lets a caller select a reference and then change an individual parameter.
// ============================================================================

/// Mel-scale convention.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MelScaleKind {
    /// librosa default — piecewise linear-then-log (Slaney 1998).
    Slaney,
    /// HTK / O'Shaughnessy–Makhoul `2595·log10(1+f/700)` (Kaldi, Praat).
    Htk,
}

/// Analysis window function.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccWindow {
    /// Periodic Hann (librosa).
    PeriodicHann,
    /// Symmetric Hann raised to 0.85 (Kaldi).
    Povey,
    /// Praat GAUSSIAN_2.
    PraatGaussian,
    /// Hamming (HTK).
    Hamming,
}

/// Frame placement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccFraming {
    /// librosa `center=True`: zero-pad win/2 each side, `n = 1 + len/hop`.
    Centered,
    /// No centering: `n = 1 + (len − win)/hop` (Kaldi snip-edges, Praat).
    SnipEdges,
}

/// FFT length rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccFft {
    /// FFT size equals the window length (librosa).
    WindowLength,
    /// Round up to the next power of two (Kaldi, Praat).
    NextPow2,
}

/// Triangular filterbank layout.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MfccFilters {
    /// `n` filters spread over `[f_min, f_max]` (librosa, Kaldi).
    NMels(usize),
    /// Centres every `step_mel` from `first_mel`, count derived up to the
    /// Nyquist mel (Praat — `n_mels` does not apply).
    MelSpacing {
        /// Centre of the first filter, in mel.
        first_mel: f32,
        /// Spacing between filter centres, in mel.
        step_mel: f32,
    },
}

/// Triangle height normalization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccFilterNorm {
    /// Slaney area norm: height `2/(f_high − f_low)` (librosa).
    AreaSlaney,
    /// Unit peak (Kaldi, Praat).
    UnitPeak,
}

/// Log compression of mel energies.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum MfccLog {
    /// `10·log10(max(e, amin)/reference)`, with an optional *global* `top_db`
    /// dynamic-range floor (librosa: ref 1, amin 1e-10, top_db 80; Praat:
    /// ref 4e-10, no top_db).
    Db {
        /// dB reference (denominator): 1.0 for librosa, 4e-10 for Praat.
        reference: f32,
        /// Energy floor applied before the log (librosa 1e-10).
        amin: f32,
        /// Optional global dynamic-range floor in dB (librosa 80).
        top_db: Option<f32>,
    },
    /// `ln(max(e, floor))` (Kaldi).
    NaturalLn {
        /// Energy floor applied before `ln` (Kaldi `f32::EPSILON`).
        floor: f32,
    },
}

/// DCT normalization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccDct {
    /// Orthonormal DCT-II (librosa, Kaldi).
    Ortho,
    /// Bare cosine sum `Σ_j P_j·cos(πm(j+0.5)/N)` (Praat).
    Unnormalized,
}

/// Power-spectrum scaling.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MfccPowerNorm {
    /// Raw `|FFT|²` (librosa, Kaldi).
    Raw,
    /// Praat: `2/(nfft·win)·|FFT|²`.
    PraatDuration,
}

/// The full MFCC parameter space. Build one with a preset
/// ([`MfccParams::librosa`] / [`kaldi`](MfccParams::kaldi) /
/// [`praat`](MfccParams::praat)) and then override individual fields, or
/// construct from scratch. Run via [`mfcc_with_params`].
#[derive(Debug, Clone, PartialEq)]
pub struct MfccParams {
    /// Base analysis-window duration in seconds (before `window_duration_factor`).
    pub frame_size_seconds: f32,
    /// Frame advance in seconds.
    pub hop_seconds: f32,
    /// Output columns (column 0 is c0).
    pub n_mfcc: usize,
    /// Lowest filterbank frequency in Hz.
    pub f_min: f32,
    /// Highest filterbank frequency in Hz (typically the Nyquist).
    pub f_max: f32,
    /// Analysis window function.
    pub window: MfccWindow,
    /// Window length = `frame_size · this · sr` (Praat uses 2.0).
    pub window_duration_factor: f32,
    /// Frame placement convention.
    pub framing: MfccFraming,
    /// FFT-length rule.
    pub fft: MfccFft,
    /// Subtract the per-frame mean before windowing (Kaldi).
    pub remove_dc: bool,
    /// Pre-emphasis coefficient `α` in `y[n] = x[n] − α·x[n−1]` (0 = none).
    pub pre_emphasis: f32,
    /// Mel-scale convention.
    pub mel_scale: MelScaleKind,
    /// Filterbank layout.
    pub filters: MfccFilters,
    /// Triangle height normalization.
    pub filter_norm: MfccFilterNorm,
    /// Triangle slopes are linear in the mel domain (Kaldi) rather than in Hz
    /// (librosa, Praat).
    pub triangle_in_mel: bool,
    /// Drop the Nyquist FFT bin from the filterbank (Kaldi does).
    pub exclude_nyquist_bin: bool,
    /// Log compression of mel energies.
    pub log: MfccLog,
    /// DCT normalization.
    pub dct: MfccDct,
    /// Power-spectrum scaling.
    pub power_norm: MfccPowerNorm,
    /// Sinusoidal cepstral lifter `L` (0 = none).
    pub lifter: f32,
}

impl MfccParams {
    /// Faithful `librosa.feature.mfcc` (0.11) parameters.
    pub fn librosa(
        frame_size_seconds: f32,
        hop_seconds: f32,
        n_mels: usize,
        n_mfcc: usize,
        f_min: f32,
        f_max: f32,
    ) -> Self {
        Self {
            frame_size_seconds,
            hop_seconds,
            n_mfcc,
            f_min,
            f_max,
            window: MfccWindow::PeriodicHann,
            window_duration_factor: 1.0,
            framing: MfccFraming::Centered,
            fft: MfccFft::WindowLength,
            remove_dc: false,
            pre_emphasis: 0.0,
            mel_scale: MelScaleKind::Slaney,
            filters: MfccFilters::NMels(n_mels),
            filter_norm: MfccFilterNorm::AreaSlaney,
            triangle_in_mel: false,
            exclude_nyquist_bin: false,
            log: MfccLog::Db {
                reference: 1.0,
                amin: 1e-10,
                top_db: Some(80.0),
            },
            dct: MfccDct::Ortho,
            power_norm: MfccPowerNorm::Raw,
            lifter: 0.0,
        }
    }

    /// Faithful Kaldi `compute-mfcc-feats` parameters.
    pub fn kaldi(
        frame_size_seconds: f32,
        hop_seconds: f32,
        n_mels: usize,
        n_mfcc: usize,
        f_min: f32,
        f_max: f32,
    ) -> Self {
        Self {
            frame_size_seconds,
            hop_seconds,
            n_mfcc,
            f_min,
            f_max,
            window: MfccWindow::Povey,
            window_duration_factor: 1.0,
            framing: MfccFraming::SnipEdges,
            fft: MfccFft::NextPow2,
            remove_dc: true,
            pre_emphasis: 0.97,
            mel_scale: MelScaleKind::Htk,
            filters: MfccFilters::NMels(n_mels),
            filter_norm: MfccFilterNorm::UnitPeak,
            triangle_in_mel: true,
            exclude_nyquist_bin: true,
            log: MfccLog::NaturalLn {
                floor: f32::EPSILON,
            },
            dct: MfccDct::Ortho,
            power_norm: MfccPowerNorm::Raw,
            lifter: 22.0,
        }
    }

    /// Praat `Sound: To MFCC…` parameters. `n_mfcc` includes c0; `n_mels`
    /// does not apply. NOTE: for best Praat fidelity call `mfcc(…, Praat)`,
    /// which uses a dedicated **f64** path; this preset run through the (f32)
    /// [`mfcc_with_params`] pipeline is a lower-precision approximation until
    /// the pipeline migrates to f64 (Praat's un-normalised dB DCT is f32-hostile
    /// — see [`MfccMethod::Praat`]).
    pub fn praat(frame_size_seconds: f32, hop_seconds: f32, n_mfcc: usize, f_max: f32) -> Self {
        Self {
            frame_size_seconds,
            hop_seconds,
            n_mfcc,
            f_min: 0.0,
            f_max,
            window: MfccWindow::PraatGaussian,
            window_duration_factor: 2.0,
            framing: MfccFraming::SnipEdges,
            fft: MfccFft::NextPow2,
            remove_dc: false,
            pre_emphasis: 0.0,
            mel_scale: MelScaleKind::Htk,
            filters: MfccFilters::MelSpacing {
                first_mel: 100.0,
                step_mel: 100.0,
            },
            filter_norm: MfccFilterNorm::UnitPeak,
            triangle_in_mel: false,
            exclude_nyquist_bin: false,
            log: MfccLog::Db {
                reference: 4e-10,
                amin: f32::MIN_POSITIVE,
                top_db: None,
            },
            dct: MfccDct::Unnormalized,
            power_norm: MfccPowerNorm::PraatDuration,
            lifter: 0.0,
        }
    }
}

/// General triangular mel filterbank, row-major `(num_filters, n_freq)`,
/// parameterised by mel scale / layout / normalization. Reproduces the
/// librosa (Slaney+area), Kaldi (HTK+unit-peak, Nyquist-excluded), and Praat
/// (HTK+unit-peak+mel-spacing) banks exactly.
fn mel_filterbank_general(
    p: &MfccParams,
    n_freq: usize,
    nfft: usize,
    sr: f32,
) -> (Vec<f32>, usize) {
    type MelFn = fn(f32) -> f32;
    let (to_mel, to_hz): (MelFn, MelFn) = match p.mel_scale {
        MelScaleKind::Slaney => (hz_to_mel_slaney, mel_to_hz_slaney),
        MelScaleKind::Htk => (hz_to_mel_praat, mel_to_hz_praat),
    };
    // Mel edges (left, centre, right) per filter, plus the Hz width (for area
    // norm). Triangle slopes are then evaluated in mel (Kaldi) or Hz (others).
    let mut mel_edges: Vec<(f32, f32, f32)> = Vec::new();
    match p.filters {
        MfccFilters::NMels(n) => {
            let mlo = to_mel(p.f_min);
            let mhi = to_mel(p.f_max);
            let e: Vec<f32> = (0..n + 2)
                .map(|i| mlo + (mhi - mlo) * i as f32 / (n + 1) as f32)
                .collect();
            for m in 0..n {
                mel_edges.push((e[m], e[m + 1], e[m + 2]));
            }
        }
        MfccFilters::MelSpacing {
            first_mel,
            step_mel,
        } => {
            let mmax = to_mel(p.f_max);
            let num = (((mmax - first_mel) / step_mel).round() as usize).max(1);
            for k in 0..num {
                let fc = first_mel + k as f32 * step_mel;
                mel_edges.push(((fc - step_mel).max(0.0), fc, (fc + step_mel).min(mmax)));
            }
        }
    }
    let num = mel_edges.len();
    let df = sr / nfft as f32;
    let top_bin = if p.exclude_nyquist_bin {
        n_freq.saturating_sub(1)
    } else {
        n_freq
    };
    let mut fb = vec![0.0_f32; num * n_freq];
    for (m, &(lm, cm, rm)) in mel_edges.iter().enumerate() {
        // Area norm uses the Hz width regardless of the slope domain (librosa).
        let height = match p.filter_norm {
            MfccFilterNorm::UnitPeak => 1.0,
            MfccFilterNorm::AreaSlaney => 2.0 / (to_hz(rm) - to_hz(lm)).max(1e-12),
        };
        // Triangle vertices in the evaluation domain.
        let (l, c, r) = if p.triangle_in_mel {
            (lm, cm, rm)
        } else {
            (to_hz(lm), to_hz(cm), to_hz(rm))
        };
        for b in 0..top_bin {
            let coord = if p.triangle_in_mel {
                to_mel(b as f32 * df)
            } else {
                b as f32 * df
            };
            let w = if coord <= l || coord >= r {
                0.0
            } else if coord <= c {
                (coord - l) / (c - l).max(1e-12)
            } else {
                (r - coord) / (r - c).max(1e-12)
            };
            fb[m * n_freq + b] = w * height;
        }
    }
    (fb, num)
}

/// DCT matrix `(n_out, num_filters)` row-major for the chosen normalization.
fn build_dct(kind: MfccDct, num_filters: usize, n_out: usize) -> Vec<f32> {
    match kind {
        MfccDct::Ortho => dct_ii_matrix(num_filters, n_out),
        MfccDct::Unnormalized => {
            let mut m = vec![0.0_f32; n_out * num_filters];
            for c in 0..n_out {
                for j in 0..num_filters {
                    m[c * num_filters + j] = (std::f32::consts::PI * c as f32 * (j as f32 + 0.5)
                        / num_filters as f32)
                        .cos();
                }
            }
            m
        }
    }
}

/// Computes MFCCs from an explicit [`MfccParams`]. Returns `(n_frames,
/// n_mfcc)` frames-first. This is the unified pipeline the named
/// [`MfccMethod`] presets are points in; use it to start from a reference
/// preset and override individual parameters.
pub fn mfcc_with_params(samples: &[f32], sample_rate: u32, p: &MfccParams) -> Array2<f32> {
    assert!(sample_rate > 0 && p.n_mfcc > 0 && p.f_max > p.f_min);
    let sr = sample_rate as f32;
    let win = (p.frame_size_seconds * p.window_duration_factor * sr).round() as usize;
    let hop = (p.hop_seconds * sr).round() as usize;
    if win == 0 || hop == 0 || samples.is_empty() {
        return Array2::zeros((0, p.n_mfcc));
    }
    let nfft = match p.fft {
        MfccFft::WindowLength => win,
        MfccFft::NextPow2 => win.next_power_of_two(),
    };
    let n_freq = nfft / 2 + 1;

    let window = match p.window {
        MfccWindow::PeriodicHann => hann_periodic(win),
        MfccWindow::Povey => povey_window(win),
        MfccWindow::PraatGaussian => praat_gaussian_window(win),
        MfccWindow::Hamming => crate::dsp::windowing::hamming(win),
    };
    let (mel_fb, num_filters) = mel_filterbank_general(p, n_freq, nfft, sr);
    if num_filters == 0 {
        return Array2::zeros((0, p.n_mfcc));
    }
    let n_out = p.n_mfcc.min(num_filters);
    let dct = build_dct(p.dct, num_filters, n_out);
    let lifter: Vec<f32> = (0..n_out)
        .map(|i| {
            if p.lifter > 0.0 {
                1.0 + (p.lifter / 2.0) * (std::f32::consts::PI * i as f32 / p.lifter).sin()
            } else {
                1.0
            }
        })
        .collect();
    let power_scale = match p.power_norm {
        MfccPowerNorm::Raw => 1.0,
        MfccPowerNorm::PraatDuration => 2.0 / (nfft as f32 * win as f32),
    };

    // Framing: Centered materialises a zero-padded source; SnipEdges reads
    // `samples` directly. Either way frame f = src[f*hop .. f*hop+win].
    let (src, n_frames): (std::borrow::Cow<[f32]>, usize) = match p.framing {
        MfccFraming::Centered => {
            let pad = win / 2;
            let nf = 1 + samples.len() / hop;
            let padded_len = ((nf - 1) * hop + win).max(samples.len() + 2 * pad);
            let mut padded = vec![0.0_f32; padded_len];
            padded[pad..pad + samples.len()].copy_from_slice(samples);
            (std::borrow::Cow::Owned(padded), nf)
        }
        MfccFraming::SnipEdges => {
            if samples.len() < win {
                return Array2::zeros((0, p.n_mfcc));
            }
            (
                std::borrow::Cow::Borrowed(samples),
                1 + (samples.len() - win) / hop,
            )
        }
    };

    let mut planner = RealFftPlanner::<f32>::new();
    let plan = planner.plan_fft_forward(nfft);
    let mut fft_in = plan.make_input_vec();
    let mut fft_out = plan.make_output_vec();
    let mut frame = vec![0.0_f32; win];
    let mut power = vec![0.0_f32; n_freq];
    let mut grid = vec![0.0_f32; n_frames * num_filters];
    let mut gmax = f32::NEG_INFINITY;
    for f in 0..n_frames {
        let start = f * hop;
        frame.copy_from_slice(&src[start..start + win]);
        if p.remove_dc {
            let mean = frame.iter().sum::<f32>() / win as f32;
            for s in frame.iter_mut() {
                *s -= mean;
            }
        }
        if p.pre_emphasis > 0.0 {
            let a = p.pre_emphasis;
            for i in (1..win).rev() {
                frame[i] -= a * frame[i - 1];
            }
            frame[0] -= a * frame[0];
        }
        for d in fft_in[win..].iter_mut() {
            *d = 0.0;
        }
        for (dst, (&s, &w)) in fft_in[..win]
            .iter_mut()
            .zip(frame.iter().zip(window.iter()))
        {
            *dst = s * w;
        }
        plan.process(&mut fft_in, &mut fft_out)
            .expect("realfft buffers sized via make_*_vec");
        for (i, c) in fft_out.iter().enumerate() {
            power[i] = (c.re * c.re + c.im * c.im) * power_scale;
        }
        for m in 0..num_filters {
            let mut e = 0.0_f32;
            for (b, &pw) in power.iter().enumerate() {
                e += pw * mel_fb[m * n_freq + b];
            }
            let v = match p.log {
                MfccLog::Db {
                    reference, amin, ..
                } => 10.0 * (e.max(amin) / reference).log10(),
                MfccLog::NaturalLn { floor } => e.max(floor).ln(),
            };
            grid[f * num_filters + m] = v;
            if v > gmax {
                gmax = v;
            }
        }
    }
    if let MfccLog::Db {
        top_db: Some(td), ..
    } = p.log
    {
        let floor = gmax - td;
        for v in grid.iter_mut() {
            if *v < floor {
                *v = floor;
            }
        }
    }

    let mut out = Array2::<f32>::zeros((n_frames, p.n_mfcc));
    for f in 0..n_frames {
        for c in 0..n_out {
            let mut acc = 0.0_f32;
            for m in 0..num_filters {
                acc += grid[f * num_filters + m] * dct[c * num_filters + m];
            }
            out[[f, c]] = acc * lifter[c];
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::f32::consts::TAU;

    /// Slaney mel scale: hz_to_mel and mel_to_hz are inverses.
    #[test]
    fn slaney_mel_scale_inversion() {
        for &hz in &[50.0_f32, 500.0, 1000.0, 4000.0, 8000.0] {
            let mel = hz_to_mel_slaney(hz);
            let back = mel_to_hz_slaney(mel);
            assert!(
                (back - hz).abs() / hz.abs().max(1.0) < 1e-4,
                "hz={hz} → mel={mel} → hz={back}"
            );
        }
    }

    /// Filterbank rows sum to ≈ 1.0 each (Slaney area normalisation).
    #[test]
    fn slaney_filterbank_rows_have_unit_area() {
        let n_mels = 40;
        let n_freq_bins = 513; // for fft_size = 1024
        let sample_rate = 16_000.0_f32;
        let fb = slaney_mel_filterbank(n_mels, n_freq_bins, sample_rate, 0.0, sample_rate / 2.0);
        // Each row's bin-spaced integral should approximate the triangle area
        // = 1.0 (height × base / 2 = (2/(right-left)) × (right-left) / 2 = 1).
        // Riemann sum at FFT-bin resolution converges to that as resolution
        // grows; for n_fft=1024 it's typically within ~15% at low mel bands.
        for m in 0..n_mels {
            let row = &fb[m * n_freq_bins..(m + 1) * n_freq_bins];
            let n_fft = (n_freq_bins - 1) * 2;
            let df = sample_rate / n_fft as f32;
            let area: f32 = row.iter().sum::<f32>() * df;
            assert!(
                area > 0.0,
                "filterbank row {m} has zero area; row = {:?}",
                row
            );
        }
    }

    #[test]
    fn mfcc_of_sine_has_expected_shape_and_higher_c0_than_silence() {
        let sr = 16_000u32;
        let n = sr as usize;
        let samples: Vec<f32> = (0..n)
            .map(|i| (TAU * 440.0_f32 * i as f32 / sr as f32).sin())
            .collect();
        let out = mfcc(
            &samples,
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        let hop_size = (0.010_f32 * sr as f32).round() as usize;
        // librosa center=True: n_frames = 1 + n/hop.
        let expected_frames = n / hop_size + 1;
        assert_eq!(out.dim(), (expected_frames, 13));

        // c0 (first cepstral coefficient) is a proxy for log-energy.
        // A pure sine should have higher c0 than silence by a wide margin.
        let silent_out = mfcc(
            &vec![0.0_f32; n],
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        let sine_c0 = out[[expected_frames / 2, 0]];
        let silent_c0 = silent_out[[silent_out.dim().0 / 2, 0]];
        assert!(
            sine_c0 > silent_c0 + 20.0,
            "sine c0 ({sine_c0}) should be > silent c0 ({silent_c0}) by 20+ units",
        );
    }

    #[test]
    fn mfcc_of_silent_input_has_uniform_log_energy_floor() {
        let sr = 16_000u32;
        let samples = vec![0.0_f32; sr as usize];
        let out = mfcc(
            &samples,
            sr,
            0.025,
            0.010,
            40,
            13,
            0.0,
            sr as f32 / 2.0,
            MfccMethod::Librosa,
        );
        // All frames silent → all log mel energies hit the floor → c0
        // identical across frames.
        let n_frames = out.dim().0;
        assert!(n_frames > 0);
        let c0 = out[[0, 0]];
        for f in 1..n_frames {
            assert!(
                (out[[f, 0]] - c0).abs() < 1e-5,
                "frame {f}: c0={}, expected {c0}",
                out[[f, 0]]
            );
        }
    }

    #[test]
    fn mfcc_of_short_input_is_centered_not_empty() {
        // librosa center=True frames even short input: n_frames = 1 + n/hop.
        let out = mfcc(
            &[0.5; 100],
            16_000,
            0.025,
            0.010,
            40,
            13,
            0.0,
            8000.0,
            MfccMethod::Librosa,
        );
        // librosa center=True frames even short input: 1 + 100/160 = 1.
        assert_eq!(out.dim(), (1, 13));
        assert!(out.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn mfcc_of_empty_input_returns_empty() {
        let out = mfcc(
            &[],
            16_000,
            0.025,
            0.010,
            40,
            13,
            0.0,
            8000.0,
            MfccMethod::Librosa,
        );
        assert_eq!(out.dim().0, 0);
    }

    #[test]
    fn reflect_pad_mirrors_without_repeating_edge() {
        // torch reflect: edge sample is the axis, not duplicated.
        assert_eq!(
            reflect_pad(&[1.0, 2.0, 3.0, 4.0], 2),
            vec![3.0, 2.0, 1.0, 2.0, 3.0, 4.0, 3.0, 2.0]
        );
    }

    #[test]
    fn whisper_target_frames_is_exact() {
        // With `target_frames`, the audio is padded/trimmed so the result
        // has exactly that many frames (Whisper's encoder needs 3000).
        let tone: Vec<f32> = (0..3200)
            .map(|i| (2.0 * std::f32::consts::PI * 220.0 * i as f32 / 16_000.0).sin())
            .collect();
        let out = log_mel_whisper(&tone, 16_000, 400, 160, 80, Some(100));
        assert_eq!(out.dim(), (100, 80));
        assert!(out.iter().all(|v| v.is_finite()));
    }

    #[test]
    fn whisper_silence_normalises_to_constant() {
        // Silence → mel 0 → log10(1e-10) = -10 everywhere → global max -10,
        // floor -18, so max(-10,-18)=-10, then (-10+4)/4 = -1.5.
        let out = log_mel_whisper(&[0.0; 8000], 16_000, 400, 160, 80, Some(50));
        assert_eq!(out.dim(), (50, 80));
        for v in out.iter() {
            assert!(
                (v - (-1.5)).abs() < 1e-5,
                "silence frame = {v}, expected -1.5"
            );
        }
    }

    #[test]
    fn whisper_short_input_returns_empty() {
        let out = log_mel_whisper(&[0.1; 100], 16_000, 400, 160, 80, None);
        assert_eq!(out.dim().0, 0);
    }
}
