# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import os
import pathlib
import typing
__all__ = [
    "AgreementReport",
    "AnnotatorProgress",
    "Assignment",
    "Audio",
    "AudioProbe",
    "Bundle",
    "Calibration",
    "Citation",
    "ConcordanceSummary",
    "Criterion",
    "DerivedSignal",
    "ExportSummary",
    "FormantFrame",
    "ImportSummary",
    "Instrument",
    "Interval",
    "LabelCheck",
    "Ltas",
    "NotebookEntry",
    "PairAgreement",
    "PerturbationReport",
    "Point",
    "ProcessingRun",
    "ProgressCounts",
    "Project",
    "QaReport",
    "Reference",
    "Rubric",
    "RubricTier",
    "RubricTierSnapshot",
    "RubricVersion",
    "Session",
    "Speaker",
    "StatusDef",
    "Target",
    "Tier",
    "TierImpact",
    "Timeline",
    "VocabEntry",
    "abi",
    "avqi",
    "blackman",
    "cpps",
    "f0",
    "formants",
    "gaussian",
    "gne",
    "h1_h2",
    "hamming",
    "hann",
    "hfno",
    "hnr",
    "hnr_d",
    "intensity",
    "kaiser",
    "load_wav",
    "log_mel_whisper",
    "ltas",
    "mfcc",
    "new_project",
    "open_project",
    "perturbation",
    "probe_wav",
    "schema_version",
    "spectrogram",
    "stft",
    "version",
    "voiced_pitch",
]

@typing.final
class AgreementReport:
    r"""
    Inter-annotation agreement between two tiers (slice S5) — the result of
    `Project.compare_tiers`. Percentages are fractions in [0, 1]; κ is in
    (-inf, 1]. Frame fields are 0.0 for point comparisons.
    """
    @property
    def tier_type(self) -> builtins.str:
        r"""
        `"interval"` or `"point"`.
        """
    @property
    def n_a(self) -> builtins.int:
        r"""
        Unit count on side A.
        """
    @property
    def n_b(self) -> builtins.int:
        r"""
        Unit count on side B.
        """
    @property
    def n_matched(self) -> builtins.int:
        r"""
        Units matched 1:1.
        """
    @property
    def n_only_a(self) -> builtins.int:
        r"""
        Units only in A (deletions).
        """
    @property
    def n_only_b(self) -> builtins.int:
        r"""
        Units only in B (insertions).
        """
    @property
    def percent_label_agreement(self) -> builtins.float:
        r"""
        Fraction of matched pairs whose labels agree.
        """
    @property
    def cohen_kappa(self) -> builtins.float:
        r"""
        Cohen's κ over matched labels.
        """
    @property
    def mean_abs_boundary_diff(self) -> builtins.float:
        r"""
        Mean absolute boundary/time deviation (seconds) over matched pairs.
        """
    @property
    def boundary_within_tolerance(self) -> builtins.float:
        r"""
        Fraction of matched boundaries/instants within the tolerance.
        """
    @property
    def boundary_tolerance_seconds(self) -> builtins.float:
        r"""
        The boundary tolerance used (seconds).
        """
    @property
    def frame_percent_agreement(self) -> builtins.float:
        r"""
        Frame-based fraction of agreeing frames (intervals only).
        """
    @property
    def frame_kappa(self) -> builtins.float:
        r"""
        Frame-based Cohen's κ (intervals only).
        """
    @property
    def frame_step_seconds(self) -> builtins.float:
        r"""
        The frame step used (seconds).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AnnotatorProgress:
    r"""
    One annotator's assignment counts across the project (slice S6) — from
    `Project.assignment_progress`.
    """
    @property
    def annotator(self) -> builtins.str:
        r"""
        The annotator.
        """
    @property
    def assigned(self) -> builtins.int:
        r"""
        Assignments not yet started.
        """
    @property
    def in_progress(self) -> builtins.int:
        r"""
        Assignments in progress.
        """
    @property
    def done(self) -> builtins.int:
        r"""
        Assignments done.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Assignment:
    r"""
    An **assignment** (slice S4b): distributes a `Target` to an annotator. A
    dedicated object; a target may carry several (overlap → agreement). Created
    by hand (`Project.add_assignment`) or in bulk (`assign_targets_randomly`).
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Assignment id (primary key).
        """
    @property
    def target_id(self) -> builtins.int:
        r"""
        The target this assignment distributes.
        """
    @property
    def annotator(self) -> builtins.str:
        r"""
        The annotator (free-text identifier).
        """
    @property
    def role(self) -> builtins.str:
        r"""
        `"primary"` or `"secondary"`.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        Per-annotator progress: `assigned` / `in_progress` / `done`.
        """
    @property
    def seed(self) -> typing.Optional[builtins.int]:
        r"""
        The `assign_targets_randomly` seed when batch-assigned, else `None`.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    @property
    def updated_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC timestamp of the last update.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Audio:
    r"""
    Audio data loaded from disk. Samples are interleaved float32 in `[-1.0, 1.0]`;
    for stereo the layout is `[L0, R0, L1, R1, ...]`. Construct via
    `sadda.load_wav(path)`.
    """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Sample rate in Hz.
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        Number of audio channels (1 = mono, 2 = stereo, …).
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of audio frames (samples per channel).
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Audio duration in seconds.
        """
    @property
    def samples(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Interleaved samples as a 1-D float32 NumPy array.
        For stereo the layout is `[L0, R0, L1, R1, ...]`.
        """
    def mono(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Mono mixdown of the audio as a 1-D float32 NumPy array.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class AudioProbe:
    r"""
    Header-only summary of a WAV file (see `sadda.probe_wav`): its size without
    the cost of decoding. Lets a caller gauge a file's in-memory footprint
    before loading it.
    """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Sample rate in Hz.
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        Number of channels.
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of frames (samples per channel).
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration in seconds.
        """
    @property
    def decoded_bytes(self) -> builtins.int:
        r"""
        Bytes a full decode would occupy (interleaved f32): the RAM cost of
        loading this file whole.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Bundle:
    r"""
    One recording inside a [`Project`]: audio header plus optional Session +
    Speaker FKs and a freeform JSON `extra` payload. Read-only view; mutate
    via `Project.add_bundle(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Bundle id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable bundle name.
        """
    @property
    def audio_relative_path(self) -> builtins.str:
        r"""
        Audio file path relative to the project root.
        """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Audio sample rate in Hz.
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        Number of audio channels.
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of audio frames (samples per channel).
        """
    @property
    def session_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional Session id this bundle belongs to.
        """
    @property
    def speaker_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional Speaker id this bundle recorded.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload (stored as text).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Calibration:
    r"""
    Microphone / signal-chain calibration mapping dB-FS to dB-SPL.
    Construct with `Calibration(reference_spl_db=…, reference_db_fs=…)`.
    """
    @property
    def reference_spl_db(self) -> builtins.float:
        r"""
        SPL of the calibration tone (dB-SPL).
        """
    @property
    def reference_db_fs(self) -> builtins.float:
        r"""
        dB-FS measured for that tone.
        """
    def __new__(cls, reference_spl_db: builtins.float, reference_db_fs: builtins.float) -> Calibration:
        r"""
        Builds a calibration from a reference tone: its known SPL and the
        dB-FS the engine measured for it.
        """
    def spl_offset_db(self) -> builtins.float:
        r"""
        dB added to a dB-FS reading to obtain dB-SPL.
        """
    def to_spl(self, db_fs: builtins.float) -> builtins.float:
        r"""
        Converts a relative dB-FS value to calibrated dB-SPL.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Citation:
    r"""
    A literature reference for an analysis a bundle used. Returned by
    `Project.citations(bundle_id)`, suitable for a paper's reference list.
    """
    @property
    def processor_id(self) -> builtins.str:
        r"""
        The processor this cites (matches `ProcessingRun.processor_id`).
        """
    @property
    def reference(self) -> builtins.str:
        r"""
        Human-readable reference string.
        """
    @property
    def doi(self) -> typing.Optional[builtins.str]:
        r"""
        Bare DOI, if one exists.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ConcordanceSummary:
    r"""
    Result of `Project.build_concordance` (P3 aggregate view). Describes the
    derived concatenated-timeline bundle that was created.
    """
    @property
    def bundle_id(self) -> builtins.int:
        r"""
        Id of the new derived bundle holding the concatenated tokens.
        """
    @property
    def n_tokens(self) -> builtins.int:
        r"""
        Number of tokens (matching intervals) concatenated.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Total duration of the concatenated timeline, in seconds.
        """
    @property
    def n_context_annotations(self) -> builtins.int:
        r"""
        Surrounding annotations clipped + remapped onto the timeline.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Criterion:
    r"""
    A criteria-engine rule (S2). Read-only view; create via
    `Project.set_criterion(...)`. `kind` is `"structured"` (a JSON rule the
    engine evaluates) or `"python"` (a function body run by
    `sadda.criteria.run_criterion`).
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Criterion id.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Unique name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Optional description.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        `"structured"` or `"python"`.
        """
    @property
    def body(self) -> builtins.str:
        r"""
        JSON rule (structured) or Python source (python).
        """
    @property
    def target_tier(self) -> builtins.str:
        r"""
        Name of the tier accepted proposals promote to.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    @property
    def updated_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC timestamp of the last update.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DerivedSignal:
    r"""
    Registration row for a Parquet sidecar holding a dense tier's data.
    Created automatically by the `Project.write_continuous_numeric` /
    `write_continuous_vector` / `write_categorical_sampled` methods.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        DerivedSignal id (primary key).
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this sidecar belongs to.
        """
    @property
    def relative_path(self) -> builtins.str:
        r"""
        Path to the Parquet sidecar, relative to the project root.
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of frames in the sidecar.
        """
    @property
    def n_dims(self) -> builtins.int:
        r"""
        Number of dimensions per frame.
        """
    @property
    def sample_rate_hz(self) -> typing.Optional[builtins.float]:
        r"""
        Sample rate in Hz; `None` for non-sampled / variable-rate signals.
        """
    @property
    def dtype(self) -> builtins.str:
        r"""
        Dtype label: `f64`, `f32`, `utf8`.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExportSummary:
    r"""
    Result of `Project.export_annotator_package` (slice S4c).
    """
    @property
    def annotator(self) -> builtins.str:
        r"""
        The annotator the package was built for.
        """
    @property
    def path(self) -> builtins.str:
        r"""
        The package directory (a self-contained sadda sub-project).
        """
    @property
    def bundles(self) -> builtins.int:
        r"""
        Number of bundles included.
        """
    @property
    def targets(self) -> builtins.int:
        r"""
        Number of targets included.
        """
    @property
    def assignments(self) -> builtins.int:
        r"""
        Number of assignments included.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class FormantFrame:
    r"""
    One frame of formant output. Variable-length `frequencies` /
    `bandwidths` per frame — frames where the LPC root-finder didn't return
    enough valid roots in the formant range are honestly empty rather than
    NaN-padded.
    """
    @property
    def time_seconds(self) -> builtins.float:
        r"""
        Time at the centre of the analysis frame, in seconds.
        """
    @property
    def frequencies(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Formant frequencies in Hz, ascending.
        """
    @property
    def bandwidths(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Bandwidths in Hz, co-indexed with `frequencies`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ImportSummary:
    r"""
    Result of `Project.import_annotator_package` (slice S4c).
    """
    @property
    def annotator(self) -> builtins.str:
        r"""
        The annotator whose work was merged in.
        """
    @property
    def bundles_matched(self) -> builtins.int:
        r"""
        Package bundles matched (by name) to a bundle in this project.
        """
    @property
    def tiers_imported(self) -> builtins.int:
        r"""
        Per-annotator tiers created or refilled.
        """
    @property
    def annotations_imported(self) -> builtins.int:
        r"""
        Annotations copied onto those tiers.
        """
    @property
    def assignments_marked_done(self) -> builtins.int:
        r"""
        Assignments advanced to `done`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Instrument:
    r"""
    A capture instrument (microphone, interface) and its optional
    calibration. Returned by `Project.instruments()` / `get_instrument()`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Instrument id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable name.
        """
    @property
    def kind(self) -> typing.Optional[builtins.str]:
        r"""
        Kind label (e.g. `"microphone"`).
        """
    @property
    def serial(self) -> typing.Optional[builtins.str]:
        r"""
        Serial number.
        """
    @property
    def calibration(self) -> typing.Optional[Calibration]:
        r"""
        Calibration, if the instrument has been calibrated.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Interval:
    r"""
    One interval annotation. Read-only view; create via
    `Project.add_interval(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this interval belongs to.
        """
    @property
    def start_seconds(self) -> builtins.float:
        r"""
        Start time in seconds.
        """
    @property
    def end_seconds(self) -> builtins.float:
        r"""
        End time in seconds.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration in seconds (`end_seconds - start_seconds`).
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id in the parent tier.
        """
    @property
    def status(self) -> typing.Optional[builtins.str]:
        r"""
        Annotation status (a rubric-defined status string), or `None`.
        """
    @property
    def note(self) -> typing.Optional[builtins.str]:
        r"""
        Free-text note, or `None`.
        """
    @property
    def processing_run_id(self) -> typing.Optional[builtins.int]:
        r"""
        Provenance link to the producing `ProcessingRun` (e.g. a criterion
        run), or `None` for a hand-made annotation.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class LabelCheck:
    r"""
    Result of checking a label against a tier's controlled vocabulary.
    """
    @property
    def has_vocabulary(self) -> builtins.bool:
        r"""
        Whether the tier has any controlled vocabulary defined.
        """
    @property
    def closed(self) -> builtins.bool:
        r"""
        Whether the tier's vocabulary is closed.
        """
    @property
    def in_vocabulary(self) -> builtins.bool:
        r"""
        Whether the label is in the vocabulary (true for empty/no label, and
        when no vocabulary is defined).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Ltas:
    r"""
    A long-term average spectrum: mean power per `bin_hz`-wide band, in
    dB. Returned by `sadda.dsp.ltas`. Level *differences* (slope, tilt,
    alpha ratio) are the meaningful quantities.
    """
    @property
    def bin_hz(self) -> builtins.float:
        r"""
        Band width in Hz.
        """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Source sample rate in Hz.
        """
    @property
    def levels_db(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        dB level per band (band `i` spans `[i·bin_hz, (i+1)·bin_hz)`).
        """
    def slope(self, low_lo: builtins.float, low_hi: builtins.float, high_lo: builtins.float, high_hi: builtins.float) -> builtins.float:
        r"""
        Spectral slope (dB): high-band / low-band energy ratio.
        """
    def tilt(self, f_lo: builtins.float, f_hi: builtins.float) -> builtins.float:
        r"""
        Spectral tilt: regression slope of band dB over `[f_lo, f_hi)`,
        in dB per kHz.
        """
    def alpha_ratio(self) -> builtins.float:
        r"""
        Alpha ratio (dB): energy above vs below 1 kHz.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class NotebookEntry:
    r"""
    A PI lab-notebook entry (slice S7): an observation / measurement / decision
    captured while exploring, promotable into a criterion or rubric guidance.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Entry id.
        """
    @property
    def target_type(self) -> builtins.str:
        r"""
        What the note is about (usually a tier name).
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        `observation` / `measurement` / `decision`.
        """
    @property
    def text(self) -> builtins.str:
        r"""
        The note prose.
        """
    @property
    def measurement(self) -> typing.Optional[builtins.str]:
        r"""
        Optional recorded measurement.
        """
    @property
    def bundle_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional context bundle.
        """
    @property
    def promoted_kind(self) -> typing.Optional[builtins.str]:
        r"""
        `criterion` / `rubric_guidance` once promoted, else `None`.
        """
    @property
    def promoted_ref(self) -> typing.Optional[builtins.str]:
        r"""
        Reference (name) of the produced artifact once promoted.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    @property
    def updated_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC timestamp of the last update.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PairAgreement:
    r"""
    Pairwise inter-annotator agreement for one tier (slice S6) — an element of
    `Project.agreement_summary`.
    """
    @property
    def annotator_a(self) -> builtins.str:
        r"""
        First annotator.
        """
    @property
    def annotator_b(self) -> builtins.str:
        r"""
        Second annotator.
        """
    @property
    def report(self) -> AgreementReport:
        r"""
        Their agreement.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PerturbationReport:
    r"""
    Jitter + shimmer over a sustained phonation. Fields are floats:
    jitter / relative shimmers are fractions (0.01 = 1%);
    `shimmer_local_db` is in dB.
    """
    @property
    def n_periods(self) -> builtins.int:
        r"""
        Glottal periods the measures were computed over.
        """
    @property
    def jitter_local(self) -> builtins.float:
        r"""
        Jitter (local) — fraction.
        """
    @property
    def jitter_rap(self) -> builtins.float:
        r"""
        Jitter (rap) — fraction.
        """
    @property
    def jitter_ppq5(self) -> builtins.float:
        r"""
        Jitter (ppq5) — fraction.
        """
    @property
    def shimmer_local(self) -> builtins.float:
        r"""
        Shimmer (local) — fraction.
        """
    @property
    def shimmer_local_db(self) -> builtins.float:
        r"""
        Shimmer (local) — dB.
        """
    @property
    def shimmer_apq3(self) -> builtins.float:
        r"""
        Shimmer (apq3) — fraction.
        """
    @property
    def shimmer_apq5(self) -> builtins.float:
        r"""
        Shimmer (apq5) — fraction.
        """
    @property
    def period_std_s(self) -> builtins.float:
        r"""
        Period standard deviation (PSD) — seconds. An ABI component.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Point:
    r"""
    One point annotation. Read-only view; create via
    `Project.add_point(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this point belongs to.
        """
    @property
    def time_seconds(self) -> builtins.float:
        r"""
        Time in seconds.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id.
        """
    @property
    def status(self) -> typing.Optional[builtins.str]:
        r"""
        Annotation status (a rubric-defined status string), or `None`.
        """
    @property
    def note(self) -> typing.Optional[builtins.str]:
        r"""
        Free-text note, or `None`.
        """
    @property
    def processing_run_id(self) -> typing.Optional[builtins.int]:
        r"""
        Provenance link to the producing `ProcessingRun` (e.g. a criterion
        run), or `None` for a hand-made annotation.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProcessingRun:
    r"""
    One row of a bundle's provenance timeline — an analysis that ran on
    the bundle. Returned by `Project.processing_runs(bundle_id)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Processing-run id (primary key).
        """
    @property
    def bundle_id(self) -> builtins.int:
        r"""
        Bundle the run targeted.
        """
    @property
    def kind(self) -> builtins.str:
        r"""
        `dsp_algorithm` | `ml_model` | `clinical_measure` | `plugin` | `live_recording`.
        """
    @property
    def processor_id(self) -> builtins.str:
        r"""
        Reverse-DNS processor id, e.g. `sadda.dsp.pitch.autocorrelation`.
        """
    @property
    def processor_version(self) -> builtins.str:
        r"""
        Sadda version at run time.
        """
    @property
    def parameters(self) -> typing.Optional[builtins.str]:
        r"""
        JSON parameters (processor-specific shape), if any.
        """
    @property
    def output_tier_ids(self) -> typing.Optional[builtins.str]:
        r"""
        JSON array of produced tier ids, if any.
        """
    @property
    def started_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC start timestamp.
        """
    @property
    def finished_at(self) -> typing.Optional[builtins.str]:
        r"""
        ISO 8601 UTC finish timestamp, if recorded.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        `ok` | `error` | `partial`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ProgressCounts:
    r"""
    A bundle's target counts by status (slice S5) — the campaign progress
    readout from `Project.target_progress`.
    """
    @property
    def total(self) -> builtins.int:
        r"""
        All targets on the bundle.
        """
    @property
    def unassigned(self) -> builtins.int:
        r"""
        `unassigned` targets.
        """
    @property
    def assigned(self) -> builtins.int:
        r"""
        `assigned` targets.
        """
    @property
    def in_progress(self) -> builtins.int:
        r"""
        `in_progress` targets.
        """
    @property
    def done(self) -> builtins.int:
        r"""
        `done` targets.
        """
    @property
    def flagged(self) -> builtins.int:
        r"""
        `flagged` targets.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Project:
    r"""
    A sadda project: a directory holding audio, derived signals, attachments,
    and a SQLite-backed corpus database. Construct via `sadda.new_project(...)`
    or `sadda.open_project(...)`.
    """
    @property
    def root(self) -> builtins.str:
        r"""
        Project's filesystem root.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Project's human-readable name (from the singleton `project` row).
        """
    @property
    def audit_user(self) -> builtins.str:
        r"""
        User string written into `audit_log.user` for mutations on this
        connection. Defaults to `"local"`.
        """
    def add_bundle(self, name: builtins.str, source_audio_path: builtins.str | os.PathLike | pathlib.Path, *, session_id: typing.Optional[builtins.int] = None, speaker_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Registers a bundle by copying `source_audio_path` into the project's
        `signals/original/` directory and recording its metadata in the corpus
        database. Returns the new bundle's id. Optional kwargs attach the
        bundle to a Session / Speaker and set a JSON `extra` payload.
        """
    def add_bundle_split(self, name_prefix: builtins.str, source_audio_path: builtins.str | os.PathLike | pathlib.Path, chunk_seconds: builtins.float) -> builtins.list[builtins.int]:
        r"""
        Splits a (typically very long) WAV into contiguous chunks of about
        `chunk_seconds` each, writing every chunk into the project as its own
        bundle named `"<name_prefix>_NNN"`. The source is streamed, so memory
        stays flat regardless of length — this is how a file too large to load
        whole still gets in. Chunk audio preserves the source format; the final
        chunk holds the remainder. Returns the new bundle ids in order.
        """
    def bundles(self) -> builtins.list[Bundle]:
        r"""
        Lists all bundles in id order.
        """
    def delete_bundle(self, bundle_id: builtins.int) -> None:
        r"""
        Permanently deletes a bundle and all its tiers, annotations,
        derived signals, and processing-run audit rows. Best-effort
        removes the underlying WAV from disk. No-op if `bundle_id`
        does not exist.
        """
    def rename_bundle(self, bundle_id: builtins.int, new_name: builtins.str) -> None:
        r"""
        Renames a bundle's display name. The underlying WAV file is
        left untouched. Raises if `bundle_id` does not exist or the
        new name is empty / whitespace-only.
        """
    def record_processing_run(self, bundle_id: builtins.int, kind: builtins.str, processor_id: builtins.str, *, parameters: typing.Optional[builtins.str] = None, input_tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None, output_tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None, output_signal_ids: typing.Optional[typing.Sequence[builtins.int]] = None, weights_checksum: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Records a completed processing run for audit provenance and
        returns its id. The engine fills in the sadda version, timestamps,
        and active recipe id. `kind` is one of `dsp_algorithm`,
        `ml_model`, `clinical_measure`, `plugin`, `live_recording`.
        """
    def processing_runs(self, bundle_id: builtins.int) -> builtins.list[ProcessingRun]:
        r"""
        Returns a bundle's processing-run timeline (provenance), oldest
        first.
        """
    def get_processing_run(self, id: builtins.int) -> typing.Optional[ProcessingRun]:
        r"""
        Reads a single `ProcessingRun` by id, or `None`. Resolves an
        annotation's `processing_run_id` to the run that produced it.
        """
    def citations(self, bundle_id: builtins.int) -> builtins.list[Citation]:
        r"""
        Returns the literature citations for the analyses a bundle used,
        deduplicated by processor and ordered by first use. Uncited
        processors (imports, recording) are omitted.
        """
    def add_instrument(self, name: builtins.str, *, kind: typing.Optional[builtins.str] = None, serial: typing.Optional[builtins.str] = None, calibration: typing.Optional[Calibration] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts an instrument (microphone / interface), optionally with a
        `Calibration`. Returns the new instrument's id.
        """
    def instruments(self) -> builtins.list[Instrument]:
        r"""
        Lists all instruments in id order.
        """
    def get_instrument(self, instrument_id: builtins.int) -> Instrument:
        r"""
        Fetches a single instrument by id.
        """
    def bundle_calibration(self, bundle_id: builtins.int) -> typing.Optional[Calibration]:
        r"""
        Resolves a bundle's calibration via bundle → session →
        instrument. `None` means levels for that bundle are dB-FS only.
        """
    def load_audio(self, bundle_id: builtins.int) -> Audio:
        r"""
        Loads the audio file for a bundle.
        """
    def add_speaker(self, name: builtins.str, *, sex: typing.Optional[builtins.str] = None, birth_year: typing.Optional[builtins.int] = None, notes: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Speaker row. Returns the new speaker's id.
        """
    def speakers(self) -> builtins.list[Speaker]:
        r"""
        Lists all speakers in id order.
        """
    def get_speaker(self, id: builtins.int) -> Speaker:
        r"""
        Fetches a single speaker by id.
        """
    def add_session(self, name: builtins.str, *, started_at: typing.Optional[builtins.str] = None, ended_at: typing.Optional[builtins.str] = None, location: typing.Optional[builtins.str] = None, instrument_id: typing.Optional[builtins.int] = None, protocol_id: typing.Optional[builtins.int] = None, notes: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Session row. Returns the new session's id.
        """
    def sessions(self) -> builtins.list[Session]:
        r"""
        Lists all sessions in id order.
        """
    def get_session(self, id: builtins.int) -> Session:
        r"""
        Fetches a single session by id.
        """
    def set_audit_user(self, user: builtins.str) -> None:
        r"""
        Sets the user string written into `audit_log.user` for subsequent
        mutations on this connection.
        """
    def pin_refdist(self, id: builtins.str, version: builtins.str) -> None:
        r"""
        Pins a reference distribution `id` to a specific `version` in
        `project.toml`, so the project reopens against the same data for
        reproducibility (C7). Overwrites any existing pin for that id.
        """
    def refdist_pins(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        The reference distributions this project has pinned, as a
        `{id: version}` dict.
        """
    def remove_refdist_pin(self, id: builtins.str) -> builtins.bool:
        r"""
        Removes a reference-distribution pin; returns whether one existed.
        """
    def extract_embeddings(self, bundle_id: builtins.int, model_id: builtins.str, tier_name: builtins.str) -> builtins.int:
        r"""
        E12: resolve `model_id` (`sadda/…` / `local://…` / `hf://…`), run it
        as an embedding extractor over `bundle_id`'s audio, and store the
        result as a new `continuous_vector` tier `tier_name`, recording an
        `ml_model` processing run. Returns the new tier id. (Provisional.)
        """
    def add_tier(self, bundle_id: builtins.int, name: builtins.str, r#type: builtins.str, *, parent_id: typing.Optional[builtins.int] = None, cardinality: typing.Optional[builtins.str] = None, schema: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Tier row. `type` is one of `interval`, `point`, `reference`,
        `continuous_numeric`, `continuous_vector`, `categorical_sampled`.
        Returns the new tier's id.
        """
    def tiers(self, bundle_id: typing.Optional[builtins.int] = None) -> builtins.list[Tier]:
        r"""
        Lists tiers, optionally restricted to a single bundle.
        """
    def get_tier(self, id: builtins.int) -> Tier:
        r"""
        Fetches a single tier by id.
        """
    def rename_tier(self, tier_id: builtins.int, new_name: builtins.str) -> None:
        r"""
        Renames a tier's display name. Raises if `tier_id` does not exist
        or the new name is empty / whitespace-only.
        """
    def delete_tier(self, tier_id: builtins.int) -> None:
        r"""
        Deletes a tier and all of its annotations (intervals / points /
        references) and any dense derived-signal sidecar. Raises if the
        tier has child tiers (delete those first) or if `tier_id` does
        not exist.
        """
    def add_interval(self, tier_id: builtins.int, start_seconds: builtins.float, end_seconds: builtins.float, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, status: typing.Optional[builtins.str] = None, note: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts an interval annotation. Enforces parent-child cardinality at
        insert time; raises `ValueError` on cardinality violation.
        """
    def intervals(self, tier_id: builtins.int) -> builtins.list[Interval]:
        r"""
        Lists intervals for a tier in (start_seconds, id) order.
        """
    def add_point(self, tier_id: builtins.int, time_seconds: builtins.float, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, status: typing.Optional[builtins.str] = None, note: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a point annotation. Enforces parent-child cardinality.
        """
    def points(self, tier_id: builtins.int) -> builtins.list[Point]:
        r"""
        Lists points for a tier in (time_seconds, id) order.
        """
    def add_reference(self, tier_id: builtins.int, target_kind: builtins.str, target_id: builtins.int, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a reference annotation pointing at another row via
        `(target_kind, target_id)`.
        """
    def references_for(self, tier_id: builtins.int) -> builtins.list[Reference]:
        r"""
        Lists references for a tier in id order. Named `references_for`
        rather than `references` (which collides with Rust's `ref` family
        of grep targets).
        """
    def set_rubric(self, name: builtins.str, version: builtins.int = 1, guidelines: typing.Optional[builtins.str] = None) -> Rubric:
        r"""
        Creates or updates the project's singleton annotation rubric.
        """
    def rubric(self) -> typing.Optional[Rubric]:
        r"""
        Reads the project's rubric, or `None` if none has been defined.
        """
    def set_rubric_statuses(self, statuses: typing.Sequence[tuple[builtins.str, typing.Optional[builtins.str], builtins.int]]) -> None:
        r"""
        Replaces the rubric's status vocabulary. `statuses` is a list of
        `(value, description, sort_order)` tuples. Requires a rubric.
        """
    def rubric_statuses(self) -> builtins.list[StatusDef]:
        r"""
        Reads the rubric's status vocabulary in (sort_order, value) order.
        """
    def set_rubric_tier(self, tier_name: builtins.str, description: typing.Optional[builtins.str] = None, closed: builtins.bool = False) -> RubricTier:
        r"""
        Creates or updates the rubric configuration for a tier name
        (guidelines + open/closed vocabulary). Requires a rubric.
        """
    def rubric_tier(self, tier_name: builtins.str) -> typing.Optional[RubricTier]:
        r"""
        Reads the rubric configuration for a tier name, or `None`.
        """
    def set_controlled_vocabulary(self, tier_name: builtins.str, entries: typing.Sequence[tuple[builtins.str, typing.Optional[builtins.str], builtins.int]]) -> None:
        r"""
        Replaces the controlled vocabulary for a tier name. `entries` is a
        list of `(value, description, sort_order)` tuples. Auto-creates an
        open rubric-tier row if needed. Requires a rubric.
        """
    def controlled_vocabulary(self, tier_name: builtins.str) -> builtins.list[VocabEntry]:
        r"""
        Reads the controlled vocabulary for a tier name.
        """
    def label_check(self, tier_name: builtins.str, label: typing.Optional[builtins.str] = None) -> LabelCheck:
        r"""
        Checks a label against a tier's controlled vocabulary.
        """
    def set_interval_status(self, id: builtins.int, status: typing.Optional[builtins.str] = None, note: typing.Optional[builtins.str] = None) -> None:
        r"""
        Sets the status + note on an interval annotation, validating the
        status against the rubric. Either may be `None` to clear it.
        """
    def set_point_status(self, id: builtins.int, status: typing.Optional[builtins.str] = None, note: typing.Optional[builtins.str] = None) -> None:
        r"""
        Sets the status + note on a point annotation, validating the status
        against the rubric. Either may be `None` to clear it.
        """
    def set_criterion(self, name: builtins.str, kind: builtins.str, body: builtins.str, target_tier: builtins.str, description: typing.Optional[builtins.str] = None) -> Criterion:
        r"""
        Creates or updates a criterion (upsert by name). `kind` is
        `"structured"` (a JSON rule) or `"python"` (a function body).
        """
    def criteria(self) -> builtins.list[Criterion]:
        r"""
        Lists all criteria in name order.
        """
    def get_criterion(self, id: builtins.int) -> typing.Optional[Criterion]:
        r"""
        Reads a criterion by id, or `None`.
        """
    def delete_criterion(self, id: builtins.int) -> None:
        r"""
        Deletes a criterion by id (idempotent).
        """
    def add_target(self, bundle_id: builtins.int, start_seconds: builtins.float, end_seconds: builtins.float, target_type: builtins.str, *, status: typing.Optional[builtins.str] = None, source: typing.Optional[builtins.str] = None, criterion_id: typing.Optional[builtins.int] = None, note: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Adds a campaign target (a region of work) on `bundle_id` over
        `[start_seconds, end_seconds)` for `target_type`. `status` defaults to
        `"unassigned"`; `source` to `"manual"`. Returns the new target id.
        """
    def targets(self, bundle_id: builtins.int) -> builtins.list[Target]:
        r"""
        Lists a bundle's targets in time order.
        """
    def get_target(self, id: builtins.int) -> typing.Optional[Target]:
        r"""
        Reads a target by id, or `None`.
        """
    def update_target_status(self, id: builtins.int, status: builtins.str) -> None:
        r"""
        Sets a target's lifecycle `status` (one of `unassigned` / `assigned` /
        `in_progress` / `done` / `flagged`). Raises if the target is missing or
        the status is invalid.
        """
    def set_target_note(self, id: builtins.int, note: typing.Optional[builtins.str] = None) -> None:
        r"""
        Sets (or clears, with `None`) a target's note.
        """
    def delete_target(self, id: builtins.int) -> None:
        r"""
        Deletes a target by id (idempotent).
        """
    def generate_targets_from_criterion(self, criterion_id: builtins.int, bundle_id: builtins.int) -> builtins.int:
        r"""
        Generates targets from a `structured` criterion's RoI selection on
        `bundle_id` — one target per surviving select interval, typed by the
        criterion's target tier and back-linked via `criterion_id`. Replaces
        this criterion's prior targets on the bundle. Returns the count.
        `python` criteria are rejected (run them in `sadda.criteria`).
        """
    def add_assignment(self, target_id: builtins.int, annotator: builtins.str, *, role: typing.Optional[builtins.str] = None, status: typing.Optional[builtins.str] = None, seed: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Assigns a target to an annotator. `role` defaults to `"primary"`,
        `status` to `"assigned"`. Advances the target `unassigned` → `assigned`.
        Raises if the target is missing or it is already assigned to `annotator`.
        Returns the new assignment id.
        """
    def assignments(self, bundle_id: builtins.int) -> builtins.list[Assignment]:
        r"""
        Lists a bundle's assignments (across all its targets).
        """
    def assignments_for_target(self, target_id: builtins.int) -> builtins.list[Assignment]:
        r"""
        Lists the assignments on a single target.
        """
    def update_assignment_status(self, id: builtins.int, status: builtins.str) -> None:
        r"""
        Sets an assignment's per-annotator `status` (`assigned` / `in_progress`
        / `done`).
        """
    def set_assignment_annotator(self, id: builtins.int, annotator: builtins.str) -> None:
        r"""
        Reassigns an assignment to a different annotator.
        """
    def delete_assignment(self, id: builtins.int) -> None:
        r"""
        Deletes an assignment (idempotent). Reverts the target to `unassigned`
        when its last assignment is removed and it was merely `assigned`.
        """
    def assign_targets_randomly(self, bundle_id: builtins.int, annotators: typing.Sequence[builtins.str], seed: builtins.int, *, role: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Distributes a bundle's currently-`unassigned` targets across `annotators`
        with a deterministic, seed-driven shuffle (reproducible — same seed +
        roster + targets → same assignment). Already-assigned targets are left
        alone, so re-running after a roster change re-randomizes the remainder.
        `role` defaults to `"primary"`. Returns the number assigned.
        """
    def export_annotator_package(self, annotator: builtins.str, dest_dir: builtins.str | os.PathLike | pathlib.Path) -> ExportSummary:
        r"""
        Exports a self-contained sub-project for `annotator` at `dest_dir` (their
        assigned bundles + audio + sparse tiers/annotations + targets/assignments
        + the rubric + a manifest). The annotator opens it as a normal sadda
        project and works offline. Returns an `ExportSummary`.
        """
    def import_annotator_package(self, package_dir: builtins.str | os.PathLike | pathlib.Path) -> ImportSummary:
        r"""
        Imports a returned annotator package at `package_dir`, landing the
        annotator's work on per-annotator tiers `"<tier> [annotator]"` (use
        `merge_tiers` to reconcile) and marking their assignments `done`.
        Returns an `ImportSummary`.
        """
    def build_concordance(self, tier_name: builtins.str, labels: typing.Sequence[builtins.str], dest_name: builtins.str, gap_seconds: builtins.float = 0.25) -> ConcordanceSummary:
        r"""
        Builds an aggregate "concordance" bundle (P3): every interval on tier
        `tier_name` across the corpus whose label is in `labels` (empty = any)
        becomes a token; the tokens' mono audio is concatenated in sequence
        (with `gap_seconds` of silence between) into a new bundle `dest_name`.
        A `"⟨source⟩"` divider tier marks each token's origin, and each token's
        surrounding annotations are clipped + remapped onto the timeline. The
        matched bundles must share one sample rate. Returns a
        `ConcordanceSummary`.
        """
    def merge_tiers(self, bundle_id: builtins.int, source_tier_names: typing.Sequence[builtins.str], dest_tier_name: builtins.str) -> builtins.int:
        r"""
        Unions the annotations of `source_tier_names` into `dest_tier_name` on
        `bundle_id` (time-ordered), creating the destination and replacing its
        contents. All sources must share one type (interval/point). Returns the
        number of annotations written.
        """
    def compare_tiers(self, bundle_id: builtins.int, tier_a_id: builtins.int, tier_b_id: builtins.int, *, boundary_tolerance_seconds: builtins.float = 0.02, frame_step_seconds: builtins.float = 0.01) -> AgreementReport:
        r"""
        Compares two tiers on `bundle_id` for agreement (slice S5): unit-based
        label κ, boundary deviation/tolerance, insertions/deletions, and — for
        interval tiers — a frame-based label κ/agreement. Returns an
        `AgreementReport`. Powers inter-annotator agreement, auto-vs-gold, and
        rubric-version impact alike.
        """
    def target_progress(self, bundle_id: builtins.int) -> ProgressCounts:
        r"""
        Counts a bundle's targets by status — the campaign progress readout.
        """
    def next_target(self, bundle_id: builtins.int, statuses: typing.Sequence[builtins.str]) -> typing.Optional[Target]:
        r"""
        The next target on `bundle_id` whose status is in `statuses` (time
        order) — the work-queue navigator. `None` when none match.
        """
    def project_target_progress(self) -> ProgressCounts:
        r"""
        Project-wide target counts by status — the QA dashboard completeness
        headline (slice S6).
        """
    def assignment_progress(self) -> builtins.list[AnnotatorProgress]:
        r"""
        Per-annotator assignment counts across the project, in annotator order.
        """
    def tier_qa(self, tier_id: builtins.int) -> QaReport:
        r"""
        QA findings for a tier: out-of-vocabulary / missing labels and (interval
        tiers) overlapping pairs.
        """
    def agreement_summary(self, bundle_id: builtins.int, base_tier_name: builtins.str) -> builtins.list[PairAgreement]:
        r"""
        Pairwise inter-annotator agreement over every `"<base> [annotator]"`
        tier on `bundle_id`.
        """
    def publish_rubric_version(self, note: typing.Optional[builtins.str] = None) -> RubricVersion:
        r"""
        Snapshots the current rubric under its current version (slice S6b),
        recording `note`. Re-publishing the same version updates that snapshot;
        bump `set_rubric(version+1)` to start a new one. Returns the snapshot.
        """
    def rubric_versions(self) -> builtins.list[RubricVersion]:
        r"""
        Lists published rubric versions in version order.
        """
    def get_rubric_version(self, version: builtins.int) -> typing.Optional[RubricVersion]:
        r"""
        Recalls a published rubric version's full snapshot, or `None`.
        """
    def rubric_impact(self, version: builtins.int) -> builtins.list[TierImpact]:
        r"""
        Reports how the current rubric differs from a published `version`: per
        tier, vocabulary added/removed and current annotations now out of
        vocabulary (needing revisiting). Raises if `version` was never published.
        """
    def add_notebook_entry(self, target_type: builtins.str, text: builtins.str, *, kind: typing.Optional[builtins.str] = None, measurement: typing.Optional[builtins.str] = None, bundle_id: typing.Optional[builtins.int] = None) -> builtins.int:
        r"""
        Records a PI lab-notebook entry about `target_type` (slice S7). `kind`
        defaults to `"observation"`. Returns the new entry id.
        """
    def notebook_entries(self, target_type: typing.Optional[builtins.str] = None) -> builtins.list[NotebookEntry]:
        r"""
        Lists notebook entries (newest first), optionally restricted to a
        `target_type`.
        """
    def get_notebook_entry(self, id: builtins.int) -> typing.Optional[NotebookEntry]:
        r"""
        Reads a notebook entry by id, or `None`.
        """
    def update_notebook_entry(self, id: builtins.int, text: builtins.str, measurement: typing.Optional[builtins.str] = None) -> None:
        r"""
        Edits a notebook entry's text and measurement.
        """
    def delete_notebook_entry(self, id: builtins.int) -> None:
        r"""
        Deletes a notebook entry by id (idempotent).
        """
    def promote_entry_to_criterion(self, entry_id: builtins.int, name: builtins.str, kind: builtins.str, body: builtins.str, target_tier: builtins.str) -> Criterion:
        r"""
        Promotes a notebook entry into a criterion (creates it + links the
        entry). Returns the criterion.
        """
    def promote_entry_to_rubric_guidance(self, entry_id: builtins.int) -> None:
        r"""
        Promotes a notebook entry into rubric-tier guidance: appends its text to
        the `target_type` tier's rubric description and links the entry.
        """
    def run_criterion(self, id: builtins.int, bundle_id: builtins.int) -> builtins.int:
        r"""
        Runs a `structured` criterion against a bundle, (re)writing its
        proposals onto the preview tier. Returns the proposal count.
        `python` criteria are run via `sadda.criteria.run_criterion`.
        """
    def set_proposals(self, bundle_id: builtins.int, target_tier: builtins.str, proposals: typing.Sequence[tuple[builtins.float, typing.Optional[builtins.float], typing.Optional[builtins.str]]], processing_run_id: typing.Optional[builtins.int] = None) -> builtins.int:
        r"""
        (Re)writes proposals onto the preview tier `"<target> (auto)"`,
        replacing prior ones. `proposals` is a list of
        `(start, end_or_None, label_or_None)` tuples — `end=None` for a point.
        `processing_run_id` stamps each proposal with its provenance link (the
        row returned by `record_criterion_run`); pass `None` for unattributed
        proposals. Used by the python-escape criterion executor.
        """
    def record_criterion_run(self, criterion_id: builtins.int, bundle_id: builtins.int) -> builtins.int:
        r"""
        Records a `processing_run` of kind `criterion_run` for an execution of
        criterion `criterion_id` against `bundle_id`, returning its id. The
        python-escape executor calls this before `set_proposals` so a python
        criterion's run is traced exactly like a structured one.
        """
    def accept_proposals(self, bundle_id: builtins.int, target_tier: builtins.str) -> builtins.int:
        r"""
        Promotes all proposals on `"<target> (auto)"` to the target tier
        (validated against its rubric), then clears the preview tier. Returns
        the number promoted.
        """
    def clear_proposals(self, bundle_id: builtins.int, target_tier: builtins.str) -> builtins.int:
        r"""
        Discards all proposals on `"<target> (auto)"`. Returns the count.
        """
    def write_continuous_numeric(self, tier_id: builtins.int, samples: numpy.typing.NDArray[numpy.float64], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `continuous_numeric` Parquet sidecar from a 1-D float64
        NumPy array and inserts the matching `DerivedSignal` row. Returns
        the new DerivedSignal id. Errors with TypeError-style messages if
        the tier isn't `continuous_numeric` or already has a sidecar.
        """
    def read_continuous_numeric(self, tier_id: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Reads a `continuous_numeric` sidecar back into a 1-D float64 NumPy
        array.
        """
    def write_continuous_vector(self, tier_id: builtins.int, frames: numpy.typing.NDArray[numpy.float64], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `continuous_vector` Parquet sidecar from a 2-D float64
        NumPy array of shape `[n_frames, n_dims]`.
        """
    def read_continuous_vector(self, tier_id: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Reads a `continuous_vector` sidecar back into a 2-D float64 NumPy
        array.
        """
    def write_categorical_sampled(self, tier_id: builtins.int, labels: typing.Sequence[builtins.str], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `categorical_sampled` Parquet sidecar from a list of
        strings.
        """
    def read_categorical_sampled(self, tier_id: builtins.int) -> builtins.list[builtins.str]:
        r"""
        Reads a `categorical_sampled` sidecar back into a list of strings.
        """
    def derived_signal(self, tier_id: builtins.int) -> typing.Optional[DerivedSignal]:
        r"""
        Returns the DerivedSignal row for a tier, or None if no sidecar
        has been written yet.
        """
    def dense_path(self, tier_id: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Returns the absolute filesystem path of a dense tier's Parquet
        sidecar (as a string), or None if no sidecar has been written yet.
        Use with `polars.scan_parquet(path)` for zero-engine-API reads.
        """
    def import_textgrid(self, path: builtins.str | os.PathLike | pathlib.Path, bundle_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Imports a Praat TextGrid into `bundle_id`. Each Praat tier becomes a
        new Tier row (interval or point); each annotation becomes an
        `annotation_interval` / `annotation_point` row. JSON sentinels in
        labels are decoded back into the `extra` field. Returns the list of
        new tier IDs in import order. Records a `processing_run` row for
        audit provenance.
        """
    def export_textgrid(self, bundle_id: builtins.int, path: builtins.str | os.PathLike | pathlib.Path, *, tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None) -> None:
        r"""
        Writes a Praat TextGrid for `bundle_id`'s sparse tiers to `path`.
        If `tier_ids` is given, only those tiers are exported. Dense tiers
        (continuous_numeric / vector / categorical_sampled) are skipped.
        Reference tiers are exported as IntervalTiers with a degenerate
        `[0.0, 0.001]` time span plus a JSON sentinel carrying their
        `(target_kind, target_id)`.
        """
    def import_eaf(self, path: builtins.str | os.PathLike | pathlib.Path, bundle_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Imports an ELAN .eaf into `bundle_id`. Tier hierarchy is preserved
        via EAF's `PARENT_REF` ↔ `tier.parent_id`. Point tiers are
        recovered from degenerate `[t, t+1ms]` alignable annotations via
        a ≤2ms heuristic. Reference tiers (`Symbolic_Association`
        linguistic type) come back as `reference` tiers. Returns the new
        tier IDs in import order (parents first per topological sort).
        Records a `processing_run` row for audit provenance.
        """
    def export_eaf(self, bundle_id: builtins.int, path: builtins.str | os.PathLike | pathlib.Path, *, tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None) -> None:
        r"""
        Writes an ELAN .eaf (EAF 2.8) for `bundle_id`'s sparse tiers to
        `path`. If `tier_ids` is given, only those tiers are exported.
        Dense tiers (continuous_numeric / vector / categorical_sampled)
        are skipped. Interval tiers with parents use the `Included_In`
        stereotype; reference tiers become `REF_ANNOTATION` tiers with
        the `Symbolic_Association` stereotype + a JSON sentinel encoding
        `(target_kind, target_id)`.
        """
    def export_csv(self, bundle_id: builtins.int, path: builtins.str | os.PathLike | pathlib.Path, *, tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None) -> None:
        r"""
        Writes a flat CSV of `bundle_id`'s sparse annotations to `path`: one
        tidy row per annotation across all interval / point / reference tiers
        (the shape pandas / polars / R expect). If `tier_ids` is given, only
        those tiers are exported. Dense tiers (continuous_* / categorical_*)
        are skipped — their samples live in Parquet sidecars (see `query`).
        """
    def export_json(self, bundle_id: builtins.int, path: builtins.str | os.PathLike | pathlib.Path, *, tier_ids: typing.Optional[typing.Sequence[builtins.int]] = None) -> None:
        r"""
        Writes a structured JSON document of `bundle_id`'s sparse annotations
        to `path`: bundle metadata plus a `tiers` array, each tier carrying
        its native rows (faithful, unlike the flattened CSV). If `tier_ids`
        is given, only those tiers are exported. Dense tiers are skipped.
        """
    def import_csv(self, path: builtins.str | os.PathLike | pathlib.Path, bundle_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Imports a flat CSV (as written by `export_csv`) into `bundle_id`. Rows
        are grouped into new tiers by `(tier_name, tier_type)`; interval /
        point rows become annotations. Returns the new tier IDs and records a
        `processing_run`. v1 imports only interval + point tiers; `status`,
        `parent_annotation_id`, and `processing_run_id` are dropped (times,
        label, note, and extra are honoured).
        """
    def import_json(self, path: builtins.str | os.PathLike | pathlib.Path, bundle_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Imports a structured JSON document (as written by `export_json`) into
        `bundle_id`. Each `tiers[]` entry becomes a new tier; its rows become
        annotations. Returns the new tier IDs and records a `processing_run`.
        Same v1 limits as `import_csv`.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class QaReport:
    r"""
    QA findings for one tier (slice S6) — from `Project.tier_qa`.
    """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        The tier inspected.
        """
    @property
    def n_annotations(self) -> builtins.int:
        r"""
        Total annotations on the tier.
        """
    @property
    def out_of_vocab(self) -> builtins.int:
        r"""
        Annotations whose label is out of the controlled vocabulary.
        """
    @property
    def missing_label(self) -> builtins.int:
        r"""
        Annotations with an empty / missing label.
        """
    @property
    def overlaps(self) -> builtins.int:
        r"""
        Overlapping interval pairs (0 for point tiers).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reference:
    r"""
    One reference annotation. Read-only view; create via
    `Project.add_reference(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this reference belongs to.
        """
    @property
    def target_kind(self) -> builtins.str:
        r"""
        Target kind: `bundle` | `session` | `speaker` | `tier` | `annotation`.
        """
    @property
    def target_id(self) -> builtins.int:
        r"""
        Target row id.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Rubric:
    r"""
    The project's annotation rubric (one per project): guidelines + the
    allowed status vocabulary + per-tier controlled vocabularies. Read-only
    view; create/update via `Project.set_rubric(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Always 1 (the rubric is a per-project singleton).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable rubric name.
        """
    @property
    def version(self) -> builtins.int:
        r"""
        Monotonic version integer.
        """
    @property
    def guidelines(self) -> typing.Optional[builtins.str]:
        r"""
        Free-text annotation guidelines, or `None`.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    @property
    def updated_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC timestamp of the last update.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RubricTier:
    r"""
    The rubric's configuration for a tier name: guidelines + open/closed
    controlled vocabulary. Read-only view; set via `Project.set_rubric_tier`.
    """
    @property
    def tier_name(self) -> builtins.str:
        r"""
        Tier name this configuration applies to.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Optional per-tier annotation guidance.
        """
    @property
    def closed_vocabulary(self) -> builtins.bool:
        r"""
        Whether the controlled vocabulary is closed (rejects out-of-vocab).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RubricTierSnapshot:
    r"""
    One tier's config within a published rubric snapshot (slice S6b).
    """
    @property
    def tier_name(self) -> builtins.str:
        r"""
        Tier name.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Per-tier guidance.
        """
    @property
    def closed_vocabulary(self) -> builtins.bool:
        r"""
        Whether the controlled vocabulary is closed.
        """
    @property
    def vocab(self) -> builtins.list[VocabEntry]:
        r"""
        The controlled vocabulary at snapshot time.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RubricVersion:
    r"""
    A published rubric version snapshot (slice S6b) — from
    `Project.publish_rubric_version` / `rubric_versions` / `get_rubric_version`.
    """
    @property
    def version(self) -> builtins.int:
        r"""
        The rubric version captured.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Rubric name at snapshot time.
        """
    @property
    def guidelines(self) -> typing.Optional[builtins.str]:
        r"""
        Guidelines prose at snapshot time.
        """
    @property
    def note(self) -> typing.Optional[builtins.str]:
        r"""
        Note recorded at publish time.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC publish timestamp.
        """
    @property
    def statuses(self) -> builtins.list[StatusDef]:
        r"""
        Status vocabulary at snapshot time.
        """
    @property
    def tiers(self) -> builtins.list[RubricTierSnapshot]:
        r"""
        Per-tier config + controlled vocabularies at snapshot time.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Session:
    r"""
    A recording session — a time-bounded block during which one or more
    bundles were captured. Read-only view; create via `Project.add_session(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Session id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable session name.
        """
    @property
    def started_at(self) -> typing.Optional[builtins.str]:
        r"""
        ISO 8601 UTC start timestamp.
        """
    @property
    def ended_at(self) -> typing.Optional[builtins.str]:
        r"""
        ISO 8601 UTC end timestamp.
        """
    @property
    def location(self) -> typing.Optional[builtins.str]:
        r"""
        Free-form location label.
        """
    @property
    def instrument_id(self) -> typing.Optional[builtins.int]:
        r"""
        FK into the instrument table.
        """
    @property
    def protocol_id(self) -> typing.Optional[builtins.int]:
        r"""
        FK into the protocol table.
        """
    @property
    def notes(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform notes.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Speaker:
    r"""
    A person who produced speech in the project (participant, patient, case
    subject, …). Read-only view; create via `Project.add_speaker(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Speaker id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable name or pseudonymous identifier.
        """
    @property
    def sex(self) -> typing.Optional[builtins.str]:
        r"""
        Sex / gender label (free text).
        """
    @property
    def birth_year(self) -> typing.Optional[builtins.int]:
        r"""
        Birth year (full integer year).
        """
    @property
    def notes(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform notes.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class StatusDef:
    r"""
    One allowed annotation-status value defined by the rubric. Read-only view.
    """
    @property
    def value(self) -> builtins.str:
        r"""
        The status string stored on annotations.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Optional description of what the status means.
        """
    @property
    def sort_order(self) -> builtins.int:
        r"""
        Display ordering (ascending).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Target:
    r"""
    A campaign **target** (slice S4a): the first-class unit of annotation work —
    a region of interest on a bundle that needs a kind of annotation, carrying a
    `status` through the campaign lifecycle. Generated from a criterion's RoI
    selection (`source = "criterion"`) or hand-marked (`source = "manual"`).
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Target id (primary key).
        """
    @property
    def bundle_id(self) -> builtins.int:
        r"""
        Bundle (file) the RoI lives on.
        """
    @property
    def start_seconds(self) -> builtins.float:
        r"""
        RoI start, in seconds.
        """
    @property
    def end_seconds(self) -> builtins.float:
        r"""
        RoI end, in seconds.
        """
    @property
    def target_type(self) -> builtins.str:
        r"""
        What kind of annotation work the RoI needs (usually a tier name).
        """
    @property
    def status(self) -> builtins.str:
        r"""
        Lifecycle: `unassigned` / `assigned` / `in_progress` / `done` / `flagged`.
        """
    @property
    def source(self) -> builtins.str:
        r"""
        Origin: `manual` or `criterion`.
        """
    @property
    def criterion_id(self) -> typing.Optional[builtins.int]:
        r"""
        Generating criterion id when `source == "criterion"`, else `None`.
        """
    @property
    def note(self) -> typing.Optional[builtins.str]:
        r"""
        Optional free-text note.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    @property
    def updated_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC timestamp of the last update.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tier:
    r"""
    One annotation tier: the header row in `tier`. Annotation rows
    belonging to it live in `annotation_interval` / `annotation_point` /
    `annotation_reference` (for the three sparse types) or a Parquet sidecar
    (the three dense types, landing in B3). Read-only view; create via
    `Project.add_tier(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Tier id (primary key).
        """
    @property
    def bundle_id(self) -> builtins.int:
        r"""
        Bundle this tier belongs to.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable tier name (unique within a bundle).
        """
    @property
    def r#type(self) -> builtins.str:
        r"""
        Tier type: one of `interval`, `point`, `reference`,
        `continuous_numeric`, `continuous_vector`, `categorical_sampled`.
        """
    @property
    def parent_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional parent tier id.
        """
    @property
    def cardinality(self) -> typing.Optional[builtins.str]:
        r"""
        Parent-child cardinality (`one_to_one` | `one_to_many` | `many_to_one`
        | `none`).
        """
    @property
    def schema(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `schema` payload.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class TierImpact:
    r"""
    How a rubric change affects one tier (slice S6b) — an element of
    `Project.rubric_impact`.
    """
    @property
    def tier_name(self) -> builtins.str:
        r"""
        Tier name.
        """
    @property
    def vocab_added(self) -> builtins.list[builtins.str]:
        r"""
        Vocabulary values added since the compared version.
        """
    @property
    def vocab_removed(self) -> builtins.list[builtins.str]:
        r"""
        Vocabulary values removed since the compared version.
        """
    @property
    def affected_annotations(self) -> builtins.int:
        r"""
        Current annotations now out of the current vocabulary.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Timeline:
    r"""
    Timeline navigation state: a cursor (playhead), a visible view window, and an
    optional `(start, end)` selection over a recording of `duration` seconds.
    
    Every action comes as a **move-to** (absolute) / **move-by** (relative) pair
    — e.g. `set_cursor(t)` vs `move_cursor_by(dt)` — so scripts can drive the
    same navigation the desktop app's keyboard does. Times are in seconds; the
    cursor and selection clamp to `[0, duration]`, and the view always stays
    within the recording.
    
    Construct with `Timeline(duration_seconds)`.
    """
    @property
    def cursor(self) -> builtins.float:
        r"""
        Cursor (playhead) position, in seconds.
        """
    @property
    def view_start(self) -> builtins.float:
        r"""
        Left edge of the visible view window, in seconds.
        """
    @property
    def view_end(self) -> builtins.float:
        r"""
        Right edge of the visible view window, in seconds (exclusive).
        """
    @property
    def duration(self) -> builtins.float:
        r"""
        Recording duration, in seconds.
        """
    @property
    def view_range(self) -> builtins.float:
        r"""
        Width of the visible window (`view_end - view_start`), in seconds.
        """
    @property
    def selection(self) -> typing.Optional[tuple[builtins.float, builtins.float]]:
        r"""
        The current selection as `(start, end)` seconds, or `None`.
        """
    def __new__(cls, duration_seconds: builtins.float) -> Timeline:
        r"""
        Builds a timeline for a recording of `duration_seconds`, with the view
        spanning the whole recording and the cursor at the start.
        """
    def reset_for_bundle(self, duration_seconds: builtins.float) -> None:
        r"""
        Re-initialises for a freshly-loaded recording: view spans the whole
        recording, cursor at 0, no selection.
        """
    def set_cursor(self, t: builtins.float) -> None:
        r"""
        Moves the cursor **to** `t` seconds (clamped to the recording).
        """
    def move_cursor_by(self, delta_seconds: builtins.float) -> None:
        r"""
        Moves the cursor **by** `delta_seconds` (negative = left).
        """
    def set_selection_start(self, t: builtins.float) -> None:
        r"""
        Sets the selection's **start** edge **to** `t`, seeding a selection at
        the cursor when none exists and clamping so `start <= end`.
        """
    def move_selection_start_by(self, delta_seconds: builtins.float) -> None:
        r"""
        Moves the selection's **start** edge **by** `delta_seconds`.
        """
    def set_selection_end(self, t: builtins.float) -> None:
        r"""
        Sets the selection's **end** edge **to** `t`, seeding a selection at the
        cursor when none exists and clamping so `end >= start`.
        """
    def move_selection_end_by(self, delta_seconds: builtins.float) -> None:
        r"""
        Moves the selection's **end** edge **by** `delta_seconds`.
        """
    def set_selection_range(self, start: builtins.float, end: builtins.float) -> None:
        r"""
        Sets the selection to exactly `[start, end]` seconds in one call (sorted
        and clamped). The selection analogue of `set_view_range`.
        """
    def set_point_selection(self, t: builtins.float) -> None:
        r"""
        Places a zero-width selection point at `t`.
        """
    def clear_selection(self) -> None:
        r"""
        Clears any selection.
        """
    def set_view_start(self, t: builtins.float) -> None:
        r"""
        Pans the view so it starts **at** `t` seconds, preserving the range.
        """
    def scroll_by(self, delta_seconds: builtins.float) -> None:
        r"""
        Pans the view **by** `delta_seconds`, preserving the range.
        """
    def set_view_range(self, start: builtins.float, end: builtins.float) -> None:
        r"""
        Frames the view to exactly `[start, end]` seconds (clamped). Use for
        "fit whole recording" (`0, duration`) or "zoom to selection".
        """
    def zoom_at(self, time_seconds: builtins.float, factor: builtins.float) -> None:
        r"""
        Zooms around `time_seconds` by `factor` (< 1 zooms in, > 1 zooms out).
        """
    def scroll_into_view(self, t: builtins.float) -> None:
        r"""
        Pans the minimum amount to bring `t` into the visible window.
        """
    def ensure_cursor_visible(self) -> None:
        r"""
        Shifts the view (if needed) so the cursor sits a quarter of the way in
        from the left edge — the playback-follow convention.
        """
    def pixel_to_time(self, pixel_x: builtins.float, plot_width_px: builtins.float) -> builtins.float:
        r"""
        Maps a pixel-x within `[0, plot_width_px)` to seconds in the view range.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class VocabEntry:
    r"""
    One controlled-vocabulary entry (an allowed label) for a tier. Read-only.
    """
    @property
    def value(self) -> builtins.str:
        r"""
        The allowed label value.
        """
    @property
    def description(self) -> typing.Optional[builtins.str]:
        r"""
        Optional gloss / description of the label.
        """
    @property
    def sort_order(self) -> builtins.int:
        r"""
        Display ordering (ascending).
        """
    def __repr__(self) -> builtins.str: ...

def abi(cpps: builtins.float, jitter_pct: builtins.float, gne: builtins.float, hfno: builtins.float, hnr_d: builtins.float, h1_h2: builtins.float, shimmer_db: builtins.float, shimmer_pct: builtins.float, psd_s: builtins.float) -> builtins.float:
    r"""
    Acoustic Breathiness Index v01 (Barsties von Latoszek et al. 2017): a
    0–10 breathiness score from its nine components. Clean-room from the
    published formula; **PROVISIONAL** — the HNR-D/Hfno definitions and the
    component unit conventions are not yet confirmed against the authors'
    artifact (so `abi_from_audio` is intentionally not provided). Units:
    CPPS / Hfno / HNR-D / H1−H2 / shimmer-dB in dB; GNE a ratio in [0,1];
    jitter and shimmer-local as percents; PSD in seconds.
    """

def avqi(cpps: builtins.float, hnr: builtins.float, shimmer_local_pct: builtins.float, shimmer_local_db: builtins.float, slope: builtins.float, tilt: builtins.float) -> builtins.float:
    r"""
    Acoustic Voice Quality Index v03.01 from its six components. Clean-room
    from the publications; **not yet confirmed against the reference Praat
    script** (exposed as PROVISIONAL). Units: CPPS / HNR / shimmer-dB /
    slope / tilt in dB, shimmer-local as a percent.
    """

def blackman(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Blackman window:
    `0.42 - 0.5*cos(2π n / (N-1)) + 0.08*cos(4π n / (N-1))`.
    """

def cpps(audio: Audio, *, pitch_floor_hz: builtins.float = 60.0, pitch_ceiling_hz: builtins.float = 330.0) -> builtins.float:
    r"""
    Smoothed cepstral peak prominence (dB) of a sustained phonation
    (Praat's `PowerCepstrogram` → `Get CPPS`). Raises `ValueError` if the
    signal is too short. Intended for sustained vowels.
    """

def f0(audio: Audio, *, frame_size_seconds: builtins.float = 0.029999999329447746, hop_size_seconds: builtins.float = 0.009999999776482582, min_freq_hz: builtins.float = 75.0, max_freq_hz: builtins.float = 500.0) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Estimates f0 over an Audio via time-domain autocorrelation.
    
    Returns `(times, frequencies)` as a 2-tuple of NumPy arrays:
    `times` is float64 in seconds, `frequencies` is float32 in Hz.
    """

def formants(audio: Audio, *, frame_size_seconds: builtins.float = 0.02500000037252903, hop_seconds: builtins.float = 0.009999999776482582, n_formants: builtins.int = 5, pre_emphasis: builtins.float = 0.9700000286102295, lpc_order: typing.Optional[builtins.int] = None, method: builtins.str = 'burg', max_bandwidth_hz: builtins.float = 1000.0, min_frequency_hz: builtins.float = 50.0) -> builtins.list[FormantFrame]:
    r"""
    Computes per-frame formants over an [`Audio`] via LPC + polynomial
    root-finding. Returns a list of `FormantFrame`s; each frame has
    variable-length `frequencies` / `bandwidths` (honestly empty for frames
    where the root-finder didn't return enough valid roots).
    
    `method` selects the LPC estimator: `"burg"` (default; Praat
    convention) or `"autocorrelation"`. `n_formants` is the maximum kept per
    frame after filtering; `lpc_order = 2 · n_formants + 2` by default.
    """

def gaussian(n: builtins.int, sigma: builtins.float) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Gaussian window of length `n` with standard deviation `sigma` (in samples).
    """

def gne(audio: Audio, *, downsample_hz: builtins.int = 10000, lpc_order: builtins.int = 13, bandwidth_hz: builtins.float = 1000.0, fshift_hz: builtins.float = 300.0) -> builtins.float:
    r"""
    Glottal-to-Noise Excitation ratio (Michaelis et al. 1997), in [0, 1] — a
    breathiness / turbulent-noise correlate and an ABI component. ~1 for
    pulsatile (glottal) excitation, toward 0 for turbulent noise. Raises
    `ValueError` if the signal is too short. Intended for sustained vowels.
    """

def h1_h2(audio: Audio, *, pitch_floor_hz: builtins.float = 75.0, pitch_ceiling_hz: builtins.float = 600.0) -> builtins.float:
    r"""
    H1–H2 (dB): level of the first harmonic minus the second, a glottal-source
    / open-quotient correlate and an ABI component. Uncorrected (no formant
    correction). Raises `ValueError` if no voiced f0 is found or the signal is
    too short. Intended for sustained vowels.
    """

def hamming(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Hamming window: `0.54 - 0.46 * cos(2π n / (N-1))`.
    """

def hann(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Hann window: `0.5 * (1 - cos(2π n / (N-1)))`.
    """

def hfno(audio: Audio) -> builtins.float:
    r"""
    High-frequency noise level Hfno-6000 (dB): the LTAS level difference
    between the 0–6 kHz and 6–10 kHz bands. Larger ⇒ less high-frequency
    noise ⇒ less breathy. An ABI component. Requires a sample rate ≥ 20 kHz;
    raises `ValueError` otherwise.
    """

def hnr(audio: Audio, *, pitch_floor_hz: builtins.float = 75.0, pitch_ceiling_hz: builtins.float = 600.0, hop_seconds: builtins.float = 0.009999999776482582) -> builtins.float:
    r"""
    Mean harmonics-to-noise ratio (dB) of a sustained phonation, via the
    Boersma-1993 cross-correlation method (Praat's `To Harmonicity
    (cc)`). Raises `ValueError` if the signal is too short or silent.
    """

def hnr_d(audio: Audio, *, pitch_floor_hz: builtins.float = 75.0, pitch_ceiling_hz: builtins.float = 600.0, band_lo_hz: builtins.float = 500.0, band_hi_hz: builtins.float = 1500.0, frame_size: builtins.int = 8192) -> builtins.float:
    r"""
    HNR-D (dB): the Dejonckere–Lebacq harmonic-to-noise ratio in the
    500–1500 Hz formant zone — an ABI component. CLEAN-ROOM / PROVISIONAL:
    reconstructed from the ABI papers' prose, not the authors' exact
    procedure. Raises `ValueError` if no voiced f0 or too few in-band
    harmonics. Intended for sustained vowels.
    """

def intensity(audio: Audio, *, frame_size_seconds: builtins.float = 0.029999999329447746, hop_seconds: builtins.float = 0.009999999776482582) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Per-frame intensity over an [`Audio`]: returns `(times, rms, db_fs)` as
    three NumPy arrays. `times` is float64 seconds at frame centres; `rms` is
    float32 linear amplitude; `db_fs` is float32 dB relative to digital
    full-scale (clamped to -200 dB on silence). dB-SPL (Praat convention)
    arrives in a later slice once microphone calibration is wired through.
    """

def kaiser(n: builtins.int, beta: builtins.float) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Kaiser window of length `n` with shape parameter `beta`.
    """

def load_wav(path: builtins.str | os.PathLike | pathlib.Path) -> Audio:
    r"""
    Loads a WAV file from disk. Returns a sadda.Audio.
    """

def log_mel_whisper(audio: Audio, *, n_fft: builtins.int = 400, hop_length: builtins.int = 160, n_mels: builtins.int = 80, target_frames: typing.Optional[builtins.int] = None) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Whisper-exact log-mel spectrogram, shape `(n_frames, n_mels)`.
    
    Byte-faithful to OpenAI Whisper's encoder front end (Slaney mel,
    power STFT with a periodic Hann window, `log10` + clamp, global
    dynamic-range floor, `(+4)/4` normalisation). Expects **16 kHz mono**
    for Whisper fidelity. `target_frames` pads/trims the audio so the
    result has exactly that many frames (Whisper uses 3000 for 30 s);
    `None` keeps the natural length.
    """

def ltas(audio: Audio, *, bin_hz: builtins.float = 100.0) -> Ltas:
    r"""
    Computes the long-term average spectrum of `audio` with `bin_hz`-wide
    bands (Welch-averaged power).
    """

def mfcc(audio: Audio, *, frame_size_seconds: builtins.float = 0.02500000037252903, hop_seconds: builtins.float = 0.009999999776482582, n_mels: builtins.int = 40, n_mfcc: builtins.int = 13, f_min: builtins.float = 0.0, f_max: typing.Optional[builtins.float] = None) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Computes Mel-Frequency Cepstral Coefficients over an [`Audio`]. Returns
    a 2-D float32 NumPy array of shape `(n_frames, n_mfcc)`, frames-first.
    
    Defaults match `librosa.feature.mfcc`: Slaney mel scale, `n_mels=40`,
    `n_mfcc=13`, `f_min=0`, `f_max=sr/2`, 25 ms frame, 10 ms hop.
    """

def new_project(path: builtins.str | os.PathLike | pathlib.Path, name: builtins.str) -> Project:
    r"""
    Creates a new sadda project at `path` (which must not already exist).
    Returns a sadda.Project handle ready for `.add_speaker(...)` /
    `.add_session(...)` / `.add_bundle(...)` calls.
    """

def open_project(path: builtins.str | os.PathLike | pathlib.Path) -> Project:
    r"""
    Opens an existing sadda project at `path`. Applies any pending schema
    migrations first, writing a `corpus.db.bak.<old_version>` backup.
    """

def perturbation(audio: Audio, *, pitch_floor_hz: builtins.float = 75.0, pitch_ceiling_hz: builtins.float = 600.0) -> PerturbationReport:
    r"""
    Computes jitter + shimmer for a sustained phonation. Raises
    `ValueError` if no voiced f0 is found or too few periods are
    detected (no-silent-fallback). Praat is the validation reference.
    """

def probe_wav(path: builtins.str | os.PathLike | pathlib.Path) -> AudioProbe:
    r"""
    Reads only a WAV file's header (no samples decoded) to learn its size.
    Returns a sadda.AudioProbe — cheap regardless of file length. Use it to
    decide whether a file is large enough to warrant splitting before loading.
    """

def schema_version() -> builtins.int:
    r"""
    Returns the highest corpus-database schema version this engine supports.
    """

def spectrogram(samples: numpy.typing.NDArray[numpy.float32], frame_size: builtins.int, hop_size: builtins.int, *, window: typing.Optional[numpy.typing.NDArray[numpy.float32]] = None) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Power spectrogram of a real-valued signal: `|X|²` of the STFT, in shape
    `(n_freq_bins, n_frames)`. If `window` is omitted, a Hann window of
    length `frame_size` is used.
    """

def stft(samples: numpy.typing.NDArray[numpy.float32], frame_size: builtins.int, hop_size: builtins.int, *, window: typing.Optional[numpy.typing.NDArray[numpy.float32]] = None) -> numpy.typing.NDArray[numpy.complex64]:
    r"""
    Short-time Fourier transform of a real-valued 1-D float32 signal.
    
    Returns the complex spectrogram with shape `(n_frames, n_freq_bins)` where
    `n_freq_bins = frame_size / 2 + 1` (the unique half of the spectrum for
    real input). If `window` is omitted, a Hann window of length `frame_size`
    is used (matches `scipy.signal.stft`'s default).
    """

def version() -> builtins.str:
    r"""
    Returns the underlying engine version string.
    """

def voiced_pitch(audio: Audio, *, frame_size_seconds: builtins.float = 0.029999999329447746, hop_size_seconds: builtins.float = 0.009999999776482582, min_freq_hz: builtins.float = 75.0, max_freq_hz: builtins.float = 500.0, method: builtins.str = 'boersma', voicing_threshold: builtins.float = 0.44999998807907104) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Estimates f0 with a voicing decision and returns `(times, frequencies,
    voicing)` as three NumPy arrays. `times` is float64 seconds at frame
    centres; `frequencies` is float32 Hz; `voicing` is float32 in `[0, 1]`.
    
    `method` selects the pitch tracker. Two algorithmic families —
    autocorrelation and cumulative-mean-normalized-difference — covering
    both Praat-faithful and librosa-faithful expectations:
    
    **Autocorrelation family:**
    - `"boersma"` (**default**) — **faithful Boersma 1993 / Praat `Sound:
      To Pitch (ac)…`** with `very_accurate = false`. Multi-candidate
      per-frame detection + Viterbi path-finder with octave-cost /
      octave-jump-cost / voiced-unvoiced-cost terms. Robust to halving /
      doubling / transient errors; Praat-validated. The default because it
      does not latch onto subharmonics of clean tones the way the simpler
      trackers below do (e.g. 150→75, 250→83.3).
    - `"windowed_autocorrelation"` — adopts Boersma 1993's window-correction
      idea (divides windowed-signal autocorrelation by window
      autocorrelation); fast single-peak tracker, but **prone to
      subharmonic / octave-down errors** (no octave cost or path-finding).
    - `"autocorrelation"` — naive time-domain autocorrelation (Phase-0
      tracker; what `sadda.dsp.f0(...)` calls).
    
    **Cumulative-mean-normalized-difference family:**
    - `"yin"` — de Cheveigné & Kawahara 2002. Difference function +
      CMNDF + absolute threshold. Simple and fast; independent
      algorithmic family from autocorrelation, useful for
      cross-validation against `"boersma"`.
    - `"pyin"` — Mauch & Dixon 2014, librosa's default. Probabilistic
      YIN with a beta-prior distribution over thresholds plus an HMM
      smoothing pass. librosa-validated.
    - `"swipe"` — Camacho & Harris 2008 SWIPE' (prime variant). Spectral
      method (a third algorithmic family): matches the `sqrt`-loudness
      ERB-scale spectrum against prime-harmonic cosine kernels. Validated
      against the author's own MATLAB run under Octave.
    
    `voicing_threshold` is informational here: the function returns voicing
    values for every frame so callers can apply their own threshold.
    """

