# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import os
import pathlib
import typing
__all__ = [
    "Audio",
    "Bundle",
    "DerivedSignal",
    "Interval",
    "Point",
    "Project",
    "Reference",
    "Session",
    "Speaker",
    "Tier",
    "blackman",
    "f0",
    "gaussian",
    "hamming",
    "hann",
    "intensity",
    "kaiser",
    "load_wav",
    "new_project",
    "open_project",
    "schema_version",
    "spectrogram",
    "stft",
    "version",
]

@typing.final
class Audio:
    r"""
    Audio data loaded from disk. Samples are interleaved float32 in `[-1.0, 1.0]`;
    for stereo the layout is `[L0, R0, L1, R1, ...]`. Construct via
    `sadda.load_wav(path)`.
    """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Sample rate in Hz.
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        Number of audio channels (1 = mono, 2 = stereo, …).
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of audio frames (samples per channel).
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Audio duration in seconds.
        """
    @property
    def samples(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Interleaved samples as a 1-D float32 NumPy array.
        For stereo the layout is `[L0, R0, L1, R1, ...]`.
        """
    def mono(self) -> numpy.typing.NDArray[numpy.float32]:
        r"""
        Mono mixdown of the audio as a 1-D float32 NumPy array.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Bundle:
    r"""
    One recording inside a [`Project`]: audio header plus optional Session +
    Speaker FKs and a freeform JSON `extra` payload. Read-only view; mutate
    via `Project.add_bundle(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Bundle id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable bundle name.
        """
    @property
    def audio_relative_path(self) -> builtins.str:
        r"""
        Audio file path relative to the project root.
        """
    @property
    def sample_rate(self) -> builtins.int:
        r"""
        Audio sample rate in Hz.
        """
    @property
    def channels(self) -> builtins.int:
        r"""
        Number of audio channels.
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of audio frames (samples per channel).
        """
    @property
    def session_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional Session id this bundle belongs to.
        """
    @property
    def speaker_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional Speaker id this bundle recorded.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload (stored as text).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DerivedSignal:
    r"""
    Registration row for a Parquet sidecar holding a dense tier's data.
    Created automatically by the `Project.write_continuous_numeric` /
    `write_continuous_vector` / `write_categorical_sampled` methods.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        DerivedSignal id (primary key).
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this sidecar belongs to.
        """
    @property
    def relative_path(self) -> builtins.str:
        r"""
        Path to the Parquet sidecar, relative to the project root.
        """
    @property
    def n_frames(self) -> builtins.int:
        r"""
        Number of frames in the sidecar.
        """
    @property
    def n_dims(self) -> builtins.int:
        r"""
        Number of dimensions per frame.
        """
    @property
    def sample_rate_hz(self) -> typing.Optional[builtins.float]:
        r"""
        Sample rate in Hz; `None` for non-sampled / variable-rate signals.
        """
    @property
    def dtype(self) -> builtins.str:
        r"""
        Dtype label: `f64`, `f32`, `utf8`.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Interval:
    r"""
    One interval annotation. Read-only view; create via
    `Project.add_interval(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this interval belongs to.
        """
    @property
    def start_seconds(self) -> builtins.float:
        r"""
        Start time in seconds.
        """
    @property
    def end_seconds(self) -> builtins.float:
        r"""
        End time in seconds.
        """
    @property
    def duration_seconds(self) -> builtins.float:
        r"""
        Duration in seconds (`end_seconds - start_seconds`).
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id in the parent tier.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Point:
    r"""
    One point annotation. Read-only view; create via
    `Project.add_point(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this point belongs to.
        """
    @property
    def time_seconds(self) -> builtins.float:
        r"""
        Time in seconds.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Project:
    r"""
    A sadda project: a directory holding audio, derived signals, attachments,
    and a SQLite-backed corpus database. Construct via `sadda.new_project(...)`
    or `sadda.open_project(...)`.
    """
    @property
    def root(self) -> builtins.str:
        r"""
        Project's filesystem root.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Project's human-readable name (from the singleton `project` row).
        """
    @property
    def audit_user(self) -> builtins.str:
        r"""
        User string written into `audit_log.user` for mutations on this
        connection. Defaults to `"local"`.
        """
    def add_bundle(self, name: builtins.str, source_audio_path: builtins.str | os.PathLike | pathlib.Path, *, session_id: typing.Optional[builtins.int] = None, speaker_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Registers a bundle by copying `source_audio_path` into the project's
        `signals/original/` directory and recording its metadata in the corpus
        database. Returns the new bundle's id. Optional kwargs attach the
        bundle to a Session / Speaker and set a JSON `extra` payload.
        """
    def bundles(self) -> builtins.list[Bundle]:
        r"""
        Lists all bundles in id order.
        """
    def load_audio(self, bundle_id: builtins.int) -> Audio:
        r"""
        Loads the audio file for a bundle.
        """
    def add_speaker(self, name: builtins.str, *, sex: typing.Optional[builtins.str] = None, birth_year: typing.Optional[builtins.int] = None, notes: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Speaker row. Returns the new speaker's id.
        """
    def speakers(self) -> builtins.list[Speaker]:
        r"""
        Lists all speakers in id order.
        """
    def get_speaker(self, id: builtins.int) -> Speaker:
        r"""
        Fetches a single speaker by id.
        """
    def add_session(self, name: builtins.str, *, started_at: typing.Optional[builtins.str] = None, ended_at: typing.Optional[builtins.str] = None, location: typing.Optional[builtins.str] = None, instrument_id: typing.Optional[builtins.int] = None, protocol_id: typing.Optional[builtins.int] = None, notes: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Session row. Returns the new session's id.
        """
    def sessions(self) -> builtins.list[Session]:
        r"""
        Lists all sessions in id order.
        """
    def get_session(self, id: builtins.int) -> Session:
        r"""
        Fetches a single session by id.
        """
    def set_audit_user(self, user: builtins.str) -> None:
        r"""
        Sets the user string written into `audit_log.user` for subsequent
        mutations on this connection.
        """
    def add_tier(self, bundle_id: builtins.int, name: builtins.str, r#type: builtins.str, *, parent_id: typing.Optional[builtins.int] = None, cardinality: typing.Optional[builtins.str] = None, schema: typing.Optional[builtins.str] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a Tier row. `type` is one of `interval`, `point`, `reference`,
        `continuous_numeric`, `continuous_vector`, `categorical_sampled`.
        Returns the new tier's id.
        """
    def tiers(self, bundle_id: typing.Optional[builtins.int] = None) -> builtins.list[Tier]:
        r"""
        Lists tiers, optionally restricted to a single bundle.
        """
    def get_tier(self, id: builtins.int) -> Tier:
        r"""
        Fetches a single tier by id.
        """
    def add_interval(self, tier_id: builtins.int, start_seconds: builtins.float, end_seconds: builtins.float, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts an interval annotation. Enforces parent-child cardinality at
        insert time; raises `ValueError` on cardinality violation.
        """
    def intervals(self, tier_id: builtins.int) -> builtins.list[Interval]:
        r"""
        Lists intervals for a tier in (start_seconds, id) order.
        """
    def add_point(self, tier_id: builtins.int, time_seconds: builtins.float, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a point annotation. Enforces parent-child cardinality.
        """
    def points(self, tier_id: builtins.int) -> builtins.list[Point]:
        r"""
        Lists points for a tier in (time_seconds, id) order.
        """
    def add_reference(self, tier_id: builtins.int, target_kind: builtins.str, target_id: builtins.int, *, label: typing.Optional[builtins.str] = None, parent_annotation_id: typing.Optional[builtins.int] = None, extra: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Inserts a reference annotation pointing at another row via
        `(target_kind, target_id)`.
        """
    def references_for(self, tier_id: builtins.int) -> builtins.list[Reference]:
        r"""
        Lists references for a tier in id order. Named `references_for`
        rather than `references` (which collides with Rust's `ref` family
        of grep targets).
        """
    def write_continuous_numeric(self, tier_id: builtins.int, samples: numpy.typing.NDArray[numpy.float64], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `continuous_numeric` Parquet sidecar from a 1-D float64
        NumPy array and inserts the matching `DerivedSignal` row. Returns
        the new DerivedSignal id. Errors with TypeError-style messages if
        the tier isn't `continuous_numeric` or already has a sidecar.
        """
    def read_continuous_numeric(self, tier_id: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Reads a `continuous_numeric` sidecar back into a 1-D float64 NumPy
        array.
        """
    def write_continuous_vector(self, tier_id: builtins.int, frames: numpy.typing.NDArray[numpy.float64], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `continuous_vector` Parquet sidecar from a 2-D float64
        NumPy array of shape `[n_frames, n_dims]`.
        """
    def read_continuous_vector(self, tier_id: builtins.int) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Reads a `continuous_vector` sidecar back into a 2-D float64 NumPy
        array.
        """
    def write_categorical_sampled(self, tier_id: builtins.int, labels: typing.Sequence[builtins.str], sample_rate_hz: builtins.float) -> builtins.int:
        r"""
        Writes a `categorical_sampled` Parquet sidecar from a list of
        strings.
        """
    def read_categorical_sampled(self, tier_id: builtins.int) -> builtins.list[builtins.str]:
        r"""
        Reads a `categorical_sampled` sidecar back into a list of strings.
        """
    def derived_signal(self, tier_id: builtins.int) -> typing.Optional[DerivedSignal]:
        r"""
        Returns the DerivedSignal row for a tier, or None if no sidecar
        has been written yet.
        """
    def dense_path(self, tier_id: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Returns the absolute filesystem path of a dense tier's Parquet
        sidecar (as a string), or None if no sidecar has been written yet.
        Use with `polars.scan_parquet(path)` for zero-engine-API reads.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reference:
    r"""
    One reference annotation. Read-only view; create via
    `Project.add_reference(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Annotation id.
        """
    @property
    def tier_id(self) -> builtins.int:
        r"""
        Tier this reference belongs to.
        """
    @property
    def target_kind(self) -> builtins.str:
        r"""
        Target kind: `bundle` | `session` | `speaker` | `tier` | `annotation`.
        """
    @property
    def target_id(self) -> builtins.int:
        r"""
        Target row id.
        """
    @property
    def label(self) -> typing.Optional[builtins.str]:
        r"""
        Label string.
        """
    @property
    def parent_annotation_id(self) -> typing.Optional[builtins.int]:
        r"""
        Parent annotation id.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Session:
    r"""
    A recording session — a time-bounded block during which one or more
    bundles were captured. Read-only view; create via `Project.add_session(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Session id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable session name.
        """
    @property
    def started_at(self) -> typing.Optional[builtins.str]:
        r"""
        ISO 8601 UTC start timestamp.
        """
    @property
    def ended_at(self) -> typing.Optional[builtins.str]:
        r"""
        ISO 8601 UTC end timestamp.
        """
    @property
    def location(self) -> typing.Optional[builtins.str]:
        r"""
        Free-form location label.
        """
    @property
    def instrument_id(self) -> typing.Optional[builtins.int]:
        r"""
        FK into the instrument table.
        """
    @property
    def protocol_id(self) -> typing.Optional[builtins.int]:
        r"""
        FK into the protocol table.
        """
    @property
    def notes(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform notes.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Speaker:
    r"""
    A person who produced speech in the project (participant, patient, case
    subject, …). Read-only view; create via `Project.add_speaker(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Speaker id (primary key).
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable name or pseudonymous identifier.
        """
    @property
    def sex(self) -> typing.Optional[builtins.str]:
        r"""
        Sex / gender label (free text).
        """
    @property
    def birth_year(self) -> typing.Optional[builtins.int]:
        r"""
        Birth year (full integer year).
        """
    @property
    def notes(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform notes.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        Freeform JSON payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Tier:
    r"""
    One annotation tier: the header row in `tier`. Annotation rows
    belonging to it live in `annotation_interval` / `annotation_point` /
    `annotation_reference` (for the three sparse types) or a Parquet sidecar
    (the three dense types, landing in B3). Read-only view; create via
    `Project.add_tier(...)`.
    """
    @property
    def id(self) -> builtins.int:
        r"""
        Tier id (primary key).
        """
    @property
    def bundle_id(self) -> builtins.int:
        r"""
        Bundle this tier belongs to.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        Human-readable tier name (unique within a bundle).
        """
    @property
    def r#type(self) -> builtins.str:
        r"""
        Tier type: one of `interval`, `point`, `reference`,
        `continuous_numeric`, `continuous_vector`, `categorical_sampled`.
        """
    @property
    def parent_id(self) -> typing.Optional[builtins.int]:
        r"""
        Optional parent tier id.
        """
    @property
    def cardinality(self) -> typing.Optional[builtins.str]:
        r"""
        Parent-child cardinality (`one_to_one` | `one_to_many` | `many_to_one`
        | `none`).
        """
    @property
    def schema(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `schema` payload.
        """
    @property
    def extra(self) -> typing.Optional[builtins.str]:
        r"""
        JSON `extra` payload.
        """
    @property
    def created_at(self) -> builtins.str:
        r"""
        ISO 8601 UTC creation timestamp.
        """
    def __repr__(self) -> builtins.str: ...

def blackman(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Blackman window:
    `0.42 - 0.5*cos(2π n / (N-1)) + 0.08*cos(4π n / (N-1))`.
    """

def f0(audio: Audio, *, frame_size_seconds: builtins.float = 0.029999999329447746, hop_size_seconds: builtins.float = 0.009999999776482582, min_freq_hz: builtins.float = 75.0, max_freq_hz: builtins.float = 500.0) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Estimates f0 over an Audio via time-domain autocorrelation.
    
    Returns `(times, frequencies)` as a 2-tuple of NumPy arrays:
    `times` is float64 in seconds, `frequencies` is float32 in Hz.
    """

def gaussian(n: builtins.int, sigma: builtins.float) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Gaussian window of length `n` with standard deviation `sigma` (in samples).
    """

def hamming(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Hamming window: `0.54 - 0.46 * cos(2π n / (N-1))`.
    """

def hann(n: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Hann window: `0.5 * (1 - cos(2π n / (N-1)))`.
    """

def intensity(audio: Audio, *, frame_size_seconds: builtins.float = 0.029999999329447746, hop_seconds: builtins.float = 0.009999999776482582) -> tuple[numpy.typing.NDArray[numpy.float64], numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Per-frame intensity over an [`Audio`]: returns `(times, rms, db_fs)` as
    three NumPy arrays. `times` is float64 seconds at frame centres; `rms` is
    float32 linear amplitude; `db_fs` is float32 dB relative to digital
    full-scale (clamped to -200 dB on silence). dB-SPL (Praat convention)
    arrives in a later slice once microphone calibration is wired through.
    """

def kaiser(n: builtins.int, beta: builtins.float) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Kaiser window of length `n` with shape parameter `beta`.
    """

def load_wav(path: builtins.str | os.PathLike | pathlib.Path) -> Audio:
    r"""
    Loads a WAV file from disk. Returns a sadda.Audio.
    """

def new_project(path: builtins.str | os.PathLike | pathlib.Path, name: builtins.str) -> Project:
    r"""
    Creates a new sadda project at `path` (which must not already exist).
    Returns a sadda.Project handle ready for `.add_speaker(...)` /
    `.add_session(...)` / `.add_bundle(...)` calls.
    """

def open_project(path: builtins.str | os.PathLike | pathlib.Path) -> Project:
    r"""
    Opens an existing sadda project at `path`. Applies any pending schema
    migrations first, writing a `corpus.db.bak.<old_version>` backup.
    """

def schema_version() -> builtins.int:
    r"""
    Returns the highest corpus-database schema version this engine supports.
    """

def spectrogram(samples: numpy.typing.NDArray[numpy.float32], frame_size: builtins.int, hop_size: builtins.int, *, window: typing.Optional[numpy.typing.NDArray[numpy.float32]] = None) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Power spectrogram of a real-valued signal: `|X|²` of the STFT, in shape
    `(n_freq_bins, n_frames)`. If `window` is omitted, a Hann window of
    length `frame_size` is used.
    """

def stft(samples: numpy.typing.NDArray[numpy.float32], frame_size: builtins.int, hop_size: builtins.int, *, window: typing.Optional[numpy.typing.NDArray[numpy.float32]] = None) -> numpy.typing.NDArray[numpy.complex64]:
    r"""
    Short-time Fourier transform of a real-valued 1-D float32 signal.
    
    Returns the complex spectrogram with shape `(n_frames, n_freq_bins)` where
    `n_freq_bins = frame_size / 2 + 1` (the unique half of the spectrum for
    real input). If `window` is omitted, a Hann window of length `frame_size`
    is used (matches `scipy.signal.stft`'s default).
    """

def version() -> builtins.str:
    r"""
    Returns the underlying engine version string.
    """

